---
title: "singletrial_cerebellum"
output: html_document
date: "2023-07-28"
---

# [fMRI] singletrial ~ subcortex {#ch43_singletrial_cerebellum}

```
author: "Heejung Jung"
date: "2023-07-17"
```

TODO: run and load for every participant
TODO: for loop for roi of interest

```{r libraries_nps_stim, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(car)
library(psych)
library(reshape)
library(PupillometryR)
library(plyr); library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
main_dir <- dirname(dirname(getwd()))
file.sources = list.files(file.path(main_dir, 'scripts', 'step02_R', 'utils'),
                          pattern="*.R",
                          full.names=TRUE,
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```

## Function {.unlisted .unnumbered}

```{r function::summary_for_plots_pvc, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
summary_for_plots_PVC <- function(df, groupwise_measurevar, subject_keyword, model_iv1, model_iv2, dv) {
    #  [ PLOT ] calculate mean and se  _________________________
    subjectwise <- meanSummary(
        df,
        c(subject_keyword, model_iv1, model_iv2), dv
    )
    groupwise <- summarySEwithin(
        data = subjectwise,
        measurevar = groupwise_measurevar,
        withinvars = c(model_iv1, model_iv2), idvar = subject_keyword
    )

    return(list(subjectwise,groupwise))
}
```

```{r function::simple_contrasts_singletrial, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
simple_contrasts_singletrial <- function(df) {
# [ CONTRASTS ]  ________________________________________________________________________________ # nolint
# contrast code ________________________________________
df$stim_factor <- factor(df$stimintensity)

# contrast code 1 linear
df$STIM_linear[df$stimintensity == "stimintensity-low"] <-  -0.5
df$STIM_linear[df$stimintensity == "stimintensity-med"] <-  0
df$STIM_linear[df$stimintensity == "stimintensity-high"] <-  0.5

# contrast code 2 quadratic
df$STIM_quadratic[df$stimintensity == "stimintensity-low"] <-  -0.33
df$STIM_quadratic[df$stimintensity == "stimintensity-med"] <-  0.66
df$STIM_quadratic[df$stimintensity == "stimintensity-high"] <-  -0.33

# cue contrast
df$CUE_high_gt_low[df$cuetype == "cuetype-low"] <-  -0.5 # social influence task
df$CUE_high_gt_low[df$cuetype == "cuetype-high"] <-  0.5 # no influence task


df$cue_name[df$cuetype == "cuetype-low"] <- "low"
df$cue_name[df$cuetype == "cuetype-high"] <- "high"

df$stim_name[df$stimintensity == "stimintensity-low"] <- "low"
df$stim_name[df$stimintensity == "stimintensity-med"] <- "med"
df$stim_name[df$stimintensity == "stimintensity-high"] <- "high"

df$cue_ordered <- factor(
        df$cue_name,
        levels = c("low", "high")
    )

df$stim_ordered <- factor(
        df$stim_name,
        levels = c("low", "med", "high")
    )

return(df)
}
```

```{r function::NPS_lineplot_34, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
two_factor_lineplot <-
  function(df, iv1, iv2, mean, error, xlab, ylab) {
    g <- ggplot(
      data = df,
      aes(
        x = .data[[iv1]],
        y = .data[[mean]],
        group = factor(.data[[iv2]]),
        color = factor(.data[[iv2]])
      ),
      cex.lab = 1.5,
      cex.axis = 2,
      cex.main = 1.5,
      cex.sub = 1.5
    ) +
      geom_errorbar(aes(
        ymin = (.data[[mean]] - .data[[error]]),
        ymax = (.data[[mean]] + .data[[error]])
      ), width = .1) +
      geom_line() +
      geom_point() +
      ggtitle(ggtitle) +
      xlab(xlab) +
      ylab(ylab) +
      #scale_color_manual(values = color) +
      theme_classic() +

      theme(aspect.ratio = .6) +
      expand_limits(x = 3.25) +
      #guides(fill = "none") +
      #guides(color = TRUE) +
      #guides(fill = guide_legend(title = "title")) +
      #scale_fill_manual(values = color) +
      scale_color_manual("",
                         values =  c(
                           "pain" = "#941100",
                           "vicarious" = "#008F51",
                           "cognitive" = "#011891"
                         )) +
      theme(
        legend.position = c(.99, .99),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      ) +
      theme(legend.key = element_rect(fill = "white", colour = "white")) +
      theme_bw()

    return(g)
  }
```

##TODO: outline

```{r}
taskname <- 'pain'
# load dataframe
datadir = "/Volumes/spacetop_projects_cue/analysis/fmri/nilearn/deriv08_parcel/cerebellum_King2019"
filename <- paste("roi-cerebellum_task-", taskname, "_*.tsv", sep = "")
common_path <- Sys.glob(file.path(datadir, "sub-*", filename))
df <- do.call("rbind", lapply(common_path, FUN = function(files) {
    as.data.frame(read.csv(files))
  }))

```

```{r}
df$sub <- sub("^(sub-\\d+).*", "\\1", df$filename)
df$ses <- sub("^.*(ses-\\d+).*", "\\1", df$filename)
df$run <- sub("^.*(run-\\d+).*", "\\1", df$filename)
df$runtype <- sub("^.*runtype-(\\w+)_.*", "\\1", df$filename)
df$trial <- sub("^.*(trial-\\d+).*", "\\1", df$filename)
df$cuetype <- sub("^.*(cuetype-\\w+)_.*", "\\1", df$filename)
df$stimintensity <- sub("^.*(stimintensity-\\w+).*", "\\1", df$filename)

```

```{r}

# parameters
main_dir <- dirname(dirname(getwd()))
analysis_folder  = paste0("model43_iv-cue-stim_dv-cerebellum")
analysis_dir <-
  file.path(main_dir,
            "analysis",
            "mixedeffect",
            analysis_folder,
            as.character(Sys.Date())) # nolint
dir.create(analysis_dir,
           showWarnings = FALSE,
           recursive = TRUE)
savedir <- analysis_dir
```

```{r}
pvc <- simple_contrasts_singletrial(df)

```

## LMER

```{r}
# ----------------------------------------------------------------------
#                               parameters
# ----------------------------------------------------------------------

for (dv in c("Region1","Region2","Region3","Region4","Region5","Region6","Region7","Region8","Region9","Region10"  )){
taskname = "pain"
ggtitle <- paste(taskname, " - cerebellum")
title <- paste(taskname, " - actual")
subject <- "sub"
w <- 10
h <- 6
stim_con1 <- "STIM_linear"
stim_con2 <- "STIM_quadratic"
iv1 <- "CUE_high_gt_low"
# dv <- "HIP.rh"
dv_keyword = paste0("cerebellum-",dv)

data <- pvc
data <- pvc[complete.cases(pvc[[dv]]), ]

model_savefname <- file.path(
  analysis_dir,
  paste(
    "lmer_task-",taskname,"_rating-",dv_keyword,"_",as.character(Sys.Date()),"_cooksd.txt",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                               lmer model
# ----------------------------------------------------------------------

cooksd <- lmer_twofactor_cooksd(
  data,  taskname,  iv1,  stim_con1,  stim_con2,  dv,
  subject,  dv_keyword,  model_savefname,
  'random_intercept',  print_lmer_output = FALSE
)
influential <- as.numeric(names(cooksd)[(cooksd > (4 / as.numeric(length(unique(
  data$sub
)))))])

data_screen <- data #data[-influential,]

# ----------------------------------------------------------------------
#                     summary statistics for plots
# ----------------------------------------------------------------------

model_iv1 <- "stim_ordered"
model_iv2 <- "cue_ordered"


# ======= NOTE: calculate mean and se ----------------------------------
NPSstimcue_subjectwise <- meanSummary(data_screen,
                                      c(subject, model_iv1, model_iv2), dv)
NPSstimcue_groupwise <- summarySEwithin(
  data = NPSstimcue_subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv1, model_iv2),
  idvar = subject
)
NPSstimcue_groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

# combined_se_calc_cooksd <-NPSstimcue_groupwise
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub"
ggtitle <- paste(taskname, " - ", dv, "Cooksd removed")
title <- paste(taskname, " - Cerebellum ", dv)
xlab <- ""
ylab <- "ROI average activation (A.U)"
ylim <- c(-10, 60)

if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4274AD", "#C5263A")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_task-", taskname, "_rating-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                            raincloudplots
# ----------------------------------------------------------------------

g <- plot_halfrainclouds_twofactor(
  NPSstimcue_subjectwise,
  NPSstimcue_groupwise,
  model_iv1,
  model_iv2,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g
print(g)

k <- plot_lineplot_twofactor(NPSstimcue_groupwise,
                        iv1 = "stim_ordered", iv2 = "cue_ordered",
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c("high" = "red",
                                  # "med" = "orange",
                                  "low" = "gray"),
                        ggtitle = title,
                        xlab = "Stimulus intensity", ylab = "Average activation (A.U.)")
k <- k + theme(aspect.ratio=.8)
print(k)
}
```
