---
title: "45_iv-task_dv-fir.Rmd"
output: html_document
date: "2023-08-04"
---

## load tsv
## concatenate 
## per time column, calculate mean and variance
## plot

```{r libraries, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(car)
library(psych)
library(reshape)
library(PupillometryR)
library(dplyr)
library(tidyselect)
library(tidyr)
library(plyr)
library(stringr)
library(lmerTest)
library(gghalves)
library(ggpubr)
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/R_rainclouds.R")
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/summaryse.R")
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/simulatedata.R")
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
file.sources = list.files(c("/Users/h/Documents/projects_local/cue_expectancy/scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```


```{r}

# parameters
main_dir <- dirname(dirname(getwd()))
datadir <- file.path(main_dir, 'analysis/fmri/nilearn/glm/fir')
analysis_folder  = paste0("model45_iv-task_dv-fir")
analysis_dir <-
  file.path(main_dir,
            "analysis",
            "mixedeffect",
            analysis_folder,
            as.character(Sys.Date())) # nolint
dir.create(analysis_dir,
           showWarnings = FALSE,
           recursive = TRUE)
savedir <- analysis_dir
```


## high stim vs low stim
```{r}
taskname = "pain"
exclude <- "sub-0001"

filename <- paste0("fir-beta_task-", taskname, "_*_cond-stimlow_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

lowdf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))

lowdf$stim <- "low_stim"

filename <- paste0("fir-beta_task-", taskname, "_*_cond-stimhigh_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

highdf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))
highdf$stim <- "high_stim"

```

```{r}
# Assuming your dataframe is named 'df'

# Load the tidyr package if not already loaded
# install.packages("tidyr")
library(tidyr)
df <- rbind(highdf, lowdf)
df_long <- pivot_longer(df, cols = starts_with("tr_"), names_to = "tr_num", values_to = "tr_value")

```


```{r}
df_long$tr_ordered <- factor(
        df_long$tr_num,
        levels = c(paste0("tr_", 0:19))
    )
df_long$stim_ordered <- factor(
        df_long$stim,
        levels = c("high_stim", "low_stim")
    )
subjectwise <- meanSummary(df_long,
                                      c("sub", "tr_ordered", "stim_ordered"), "tr_value")
groupwise <- summarySEwithin(
  data = subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c("stim_ordered", "tr_ordered"),
  idvar = "sub"
)
groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

```


```{r, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
two_factor_lineplot <-
  function(df, iv1, iv2, mean, error, xlab, ylab, ggtitle) {
    
n_points <- 100  # Number of points for interpolation
# interpolated_data <- data.frame(
#   
#   x = rep(seq(min(df[[iv1]]), max(df[[iv1]]), length.out = n_points), each = n_points),
#   y = rep(df[[mean]], each = n_points),
#   ymin = rep(df[[mean]] - df[[error]], each = n_points),
#   ymax = rep(df[[mean]] + df[[error]], each = n_points)
# )
    g <- ggplot(
      data = df,
      aes(
        x = .data[[iv1]],
        y = .data[[mean]],
        group = factor(.data[[iv2]]),
        color = factor(.data[[iv2]])
      ),
      cex.lab = 1.5,
      cex.axis = 2,
      cex.main = 1.5,
      cex.sub = 1.5
    ) +
      # geom_errorbar(aes(
      #   ymin = (.data[[mean]] - .data[[error]]),
      #   ymax = (.data[[mean]] + .data[[error]])
      # ), width = .1) +
      geom_ribbon(aes(
        ymin = (.data[[mean]] - .data[[error]]),
        ymax = (.data[[mean]] + .data[[error]]),
        fill =  factor(.data[[iv2]])
      ), width = .1, alpha=0.1) +
      # geom_ribbon(data = interpolated_data,
      #   aes(
      #   ymin =ymin,
      #   ymax =ymax
      # ), width = .1) +
      geom_line() +
      geom_point() +
      ggtitle(ggtitle) +
      xlab(xlab) +
      ylab(ylab) +
      #scale_color_manual(values = color) +
      theme_classic() +
      
      theme(aspect.ratio = .6) +
      expand_limits(x = 3.25) +

      scale_color_manual("",
                         values =  c("#941100", "#011891"
                         )) +
            scale_fill_manual("",
                         values =  c("#941100", "#011891"
                         )) +
      theme(
        legend.position = c(.99, .99),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      ) +
      theme(legend.key = element_rect(fill = "white", colour = "white")) +
      theme_bw()
    
    return(g)
  }
```
```{r echo=FALSE}
library(ggpubr)


# DATA = as.data.frame(combined_se_calc_cooksd)
# color = c( "#4575B4", "#D73027")
LINEIV1 = "tr_ordered"
LINEIV2 = "stim_ordered"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
p1 = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Correlation between \ncue and stimulus", ggtitle="time_series", color=c("red", "blue"))
p1
time_points <- seq(0, 0.46 * 19, 0.46)

# Modify the x-axis labels using scale_x_discrete()
p1 + scale_x_discrete(labels = setNames(time_points, colnames(df)[4:23]))+ theme_classic() 
```
```{r}
# Assuming you have a dataframe named 'data' containing the 20 data points, 'x' and 'y' values, and corresponding standard deviations 'sd'

# Load the ggplot2 library
# install.packages("ggplot2")
library(ggplot2)

# Create the plot
# y = "mean_per_sub_mean"z
ggplot(groupwise, aes(x=tr_ordered,y=mean_per_sub_mean, group = stim_ordered, colour=stim_ordered)) +
  stat_smooth(method="loess", span=0.25, se=TRUE, aes(color=stim_ordered), alpha=0.3) +
  theme_bw()

```
```{r}
# ggplot(data=groupwise, aes(x=tr_ordered, y=mean_per_sub_mean, ymin=se, ymax=se, fill=stim_ordered, linetype=stim_ordered)) + 
#  geom_line() + 
#  geom_ribbon(alpha=0.5)  
# Assuming you have a dataframe named 'data' containing the 20 mean data points and corresponding standard errors
# 'x' represents the x-values (e.g., time points)
# 'mean_y' represents the mean y-values
# 'se_y' represents the standard errors of the mean y-values

# Load the ggplot2 library
# install.packages("ggplot2")
library(ggplot2)
# groupwise$x <- as.numeric(groupwise$x)
# 
# # Sort the dataframe by the 'x' variable (if it's not already sorted)
# data <- data[order(data$x), ]

# Create the plot
# Create the plot with custom span and smoothing method
ggplot(groupwise, aes(x=tr_ordered,y=mean_per_sub_mean)) +
  geom_line() +                                   # Plot the smooth line for the mean
  geom_ribbon(aes(ymin = mean_per_sub_mean - se, ymax = mean_per_sub_mean + se), alpha = 0.3) + # Add the ribbon for standard error
  geom_smooth(method = "loess", span = 0.1, se = FALSE) +       # Add the loess smoothing curve
  labs(x = "X-axis Label", y = "Y-axis Label", title = "Smooth Line with Standard Error Ribbon") +
  theme_minimal()

```



## high cue vs low cue
```{r}
# load dataframes
taskname = "pain"
exclude <- "sub-0001"

filename <- paste0("fir-beta_task-", taskname, "_*_cond-cuelow_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

lowcuedf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))

lowcuedf$cue <- "low_cue"

filename <- paste0("fir-beta_task-", taskname, "_*_cond-cuehigh_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

highcuedf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))
highcuedf$cue <- "high_cue"

# concatenate dataframes
dfcue <- rbind(highcuedf, lowcuedf)
dfcue_long <- pivot_longer(dfcue, cols = starts_with("tr_"), names_to = "tr_num", values_to = "tr_value")

```


```{r}
# we want to order the levels so that they make sense in the plots
dfcue_long$tr_ordered <- factor(
        dfcue_long$tr_num,
        levels = c(paste0("tr_", 0:19))
    )
dfcue_long$cue_ordered <- factor(
        dfcue_long$cue,
        levels = c("high_cue", "low_cue")
    )
subjectwise.cue <- meanSummary(dfcue_long,
                                      c("sub", "tr_ordered", "cue_ordered"), "tr_value")
groupwise.cue <- summarySEwithin(
  data = subjectwise.cue,
  measurevar = "mean_per_sub",
  withinvars = c("cue_ordered", "tr_ordered"),
  idvar = "sub"
)
groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

```


```{r function::NPS_lineplot_34, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
two_factor_lineplot <-
  function(df, iv1, iv2, mean, error, xlab, ylab, ggtitle) {
    
n_points <- 100  # Number of points for interpolation
    g <- ggplot(
      data = df,
      aes(
        x = .data[[iv1]],
        y = .data[[mean]],
        group = factor(.data[[iv2]]),
        color = factor(.data[[iv2]])
      ),
      cex.lab = 1.5,
      cex.axis = 2,
      cex.main = 1.5,
      cex.sub = 1.5
    ) +

      geom_ribbon(aes(
        ymin = (.data[[mean]] - .data[[error]]),
        ymax = (.data[[mean]] + .data[[error]]),
        fill =  factor(.data[[iv2]])
      ), width = .1, alpha=0.1) +

      geom_line() +
      geom_point() +
      ggtitle(ggtitle) +
      xlab(xlab) +
      ylab(ylab) +

      theme_classic() +
      
      theme(aspect.ratio = .6) +
      expand_limits(x = 3.25) +

      scale_color_manual("",
                         values =  c("#941100", "#011891"
                         )) +
            scale_fill_manual("",
                         values =  c("#941100", "#011891"
                         )) +
      theme(
        legend.position = c(.99, .99),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
      ) +
      theme(legend.key = element_rect(fill = "white", colour = "white")) +
      theme_bw()
    
    return(g)
  }
```

```{r echo=FALSE}
LINEIV1 = "tr_ordered"
LINEIV2 = "cue_ordered"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
p1 = two_factor_lineplot(groupwise.cue, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Beta coefficients", ggtitle="time_series")
p1
time_points <- seq(0, 0.46 * 19, 0.46)

# Modify the x-axis labels using scale_x_discrete()
p1 + scale_x_discrete(labels = setNames(time_points, colnames(df)[4:23]))+ theme_classic() 
```


