# [fMRI] FIR ~ task {#ch47_fir_glasser}
---
title: "47_iv-cue-stim_dv-firglasserSPM"
output: html_document
date: "2023-08-13"
---


## load tsv
## concatenate 
## per time column, calculate mean and variance
## plot

```{r libraries, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(car)
library(psych)
library(reshape)
library(PupillometryR)
library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
library(ggpubr)
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/R_rainclouds.R")
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/summaryse.R")
# source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/simulatedata.R")
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
file.sources = list.files(c("/Users/h/Documents/projects_local/cue_expectancy/scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```

## parameters {TODO: ignore}
```{r}

# parameters
main_dir <- dirname(dirname(getwd()))
datadir <- file.path(main_dir, 'analysis/fmri/nilearn/glm/fir')
analysis_folder  = paste0("model47_iv-cue-stim_dv-firglasserSPM")
analysis_dir <-
  file.path(main_dir,
            "analysis",
            "mixedeffect",
            analysis_folder,
            as.character(Sys.Date())) # nolint
dir.create(analysis_dir,
           showWarnings = FALSE,
           recursive = TRUE)
savedir <- analysis_dir
```


## epoch: stim, high stim vs low stim
```{r}
# ------------------------------------------------------------------------------
#                       epoch stim, high stim vs low stim
# ------------------------------------------------------------------------------
datadir = "/Volumes/spacetop_projects_cue/analysis/fmri/spm/fir/ttl1"
taskname = "pain"
exclude <- "sub-0001"
filename <- paste0("sub-*_runtype-", taskname, "*roi-MT_tr-42.csv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

df <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = ",")
    }))
```


```{r}

parsed_df <- df %>%
  separate(condition, into = c("cue", "stim"), sep = "_", remove = FALSE)

```


```{r}
TR_length <- 42
# --------------------- subset regions based on ROI ----------------------------
df_long <- pivot_longer(parsed_df, cols = starts_with("tr"), names_to = "tr_num", values_to = "tr_value")

# ----------------------------- clean factor -----------------------------------
df_long$tr_ordered <- factor(
        df_long$tr_num,
        levels = c(paste0("tr", 1:TR_length))
    )
df_long$stim_ordered <- factor(
        df_long$stim,
        levels = c("stimH", "stimM", "stimL")
    )

# --------------------------- summary statistics -------------------------------
subjectwise <- meanSummary(df_long,
                                      c("sub", "tr_ordered", "stim_ordered"), "tr_value")
groupwise <- summarySEwithin(
  data = subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c("stim_ordered", "tr_ordered"),
  idvar = "sub"
)
groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

# --------------------------------- plot ---------------------------------------
LINEIV1 = "tr_ordered"
LINEIV2 = "stim_ordered"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
sorted_indices <- order(groupwise$tr_ordered)
groupwise_sorted <- groupwise[sorted_indices, ]
p1 = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Epoch: stimulus, High stim vs. Low stim", ggtitle="time_series", color=c("#5f0f40","#ae2012", "#fcbf49"))
time_points <- seq(1, 0.46 * TR_length, 0.46)
p1 + scale_x_discrete(labels = setNames(time_points, colnames(df_long)[7:7+TR_length]))+ theme_classic()
p1 + theme_classic()
```







### PCA subjectwise
```{r}
# install.packages("ggplot2")    # Install ggplot2 if you haven't already
# install.packages("FactoMineR") # Install FactoMineR if you haven't already
library(ggplot2)
library(FactoMineR)



# Assuming your original dataframe is named 'df'

# Convert the dataframe to wide format
df_wide <- pivot_wider(subjectwise, 
                       id_cols = c("tr_ordered", "stim_ordered"), 
                       names_from = "sub", 
                       values_from = "mean_per_sub")

df_wide <- pivot_wider(subjectwise, 
                       id_cols = c("sub", "stim_ordered"), 
                       names_from = "tr_ordered", 
                       values_from = "mean_per_sub")
stim_high.df <- df_wide[df_wide$stim_ordered == "stimH",]
stim_low.df <- df_wide[df_wide$stim_ordered == "stimL",]
# selected_columns <- subset(stim_high.df, select = 2:(ncol(stim_high.df) - 1))
meanhighdf <- data.frame(subset(stim_high.df, select = 3:(ncol(stim_high.df) - 1)))
high.pca_result <- prcomp(meanhighdf)
high.pca_scores <- as.data.frame(high.pca_result$x)
# Access the proportion of variance explained by each principal component
high.variance_explained <- high.pca_result$sdev^2 / sum(high.pca_result$sdev^2)
plot(high.variance_explained)
# Access the standard deviations of each principal component
high.stdev <- high.pca_result$sdev

meanlowdf <- data.frame(subset(stim_low.df, select = 3:(ncol(stim_low.df) - 1)))
low.pca <- prcomp(meanlowdf)
low.pca_scores <- as.data.frame(low.pca$x)
library(plotly)  # You can use plotly to create an interactive 3D plot
# plot_ly(high.pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers")
# plot_ly(low.pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers")
combined_pca_scores <- rbind(high.pca_scores, low.pca_scores)

# Add a new column to indicate the stim_ordered category (high_stim or low_stim)
combined_pca_scores$stim_ordered <- c(rep("high_stim", nrow(high.pca_scores)), rep("low_stim", nrow(low.pca_scores)))

# Create the 3D PCA plot
plot_ly(combined_pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers",
        color = ~stim_ordered)
# data_matrix <- groupwise[groupwise$stim_ordered == "high_stim",c("tr_ordered", "mean_per_sub_norm_mean")]
# sorted_indices <- order(data_matrix$tr_ordered)
# df_ordered <- data_matrix[sorted_indices, ]
# pca_result <- PCA(data_matrix$mean_per_sub_norm_mean)
# datapoints <- df$datapoints
```

### PCA groupwise
```{r}
# install.packages("ggplot2")    # Install ggplot2 if you haven't already
# install.packages("FactoMineR") # Install FactoMineR if you haven't already
library(ggplot2)
library(FactoMineR)



# Assuming your original dataframe is named 'df'

# Convert the dataframe to wide format
df_wide.group <- pivot_wider(subjectwise,
                       id_cols = c("tr_ordered", "stim_ordered"),
                       names_from = "sub",
                       values_from = "mean_per_sub")
# ------
# data_matrix <- groupwise[groupwise$stim_ordered == "high_stim",c("tr_ordered", "mean_per_sub_norm_mean")]
# sorted_indices <- order(data_matrix$tr_ordered)
# df_ordered <- data_matrix[sorted_indices, ]
# datapoints <- df_ordered$mean_per_sub_norm_mean
# data_df <- data.frame(Dim1 = datapoints, Dim2 = datapoints, Dim3 = datapoints)
# pca <- prcomp(data_df)
# pca_scores <- as.data.frame(pca$x)
# plot_ly(pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers")
# -------
stim_high.df <- df_wide[df_wide$stim_ordered == "stimH",]
stim_low.df <- df_wide[df_wide$stim_ordered == "stimL",]
# selected_columns <- subset(stim_high.df, select = 2:(ncol(stim_high.df) - 1))
meanhighdf <- data.frame(subset(stim_high.df, select = 3:(ncol(stim_high.df) - 1)))
high.pca <- prcomp(meanhighdf)
high.pca_scores <- as.data.frame(high.pca$x)

meanlowdf <- data.frame(subset(stim_low.df, select = 3:(ncol(stim_low.df) - 1)))
low.pca <- prcomp(meanlowdf)
low.pca_scores <- as.data.frame(low.pca$x)
library(plotly)  # You can use plotly to create an interactive 3D plot
# plot_ly(high.pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers")
# plot_ly(low.pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers")
combined_pca_scores <- rbind(high.pca_scores, low.pca_scores)

# Add a new column to indicate the stim_ordered category (high_stim or low_stim)
combined_pca_scores$stim_ordered <- c(rep("high_stim", nrow(high.pca_scores)), rep("low_stim", nrow(low.pca_scores)))

# Create the 3D PCA plot
plot_ly(combined_pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers",
        color = ~stim_ordered)
# data_matrix <- groupwise[groupwise$stim_ordered == "high_stim",c("tr_ordered", "mean_per_sub_norm_mean")]
# sorted_indices <- order(data_matrix$tr_ordered)
# df_ordered <- data_matrix[sorted_indices, ]
# pca_result <- PCA(data_matrix$mean_per_sub_norm_mean)
# datapoints <- df$datapoints

# Assuming you have a dataframe named 'data' containing the 20 data points, 'x' and 'y' values, and corresponding standard deviations 'sd'

# Load the ggplot2 library
# install.packages("ggplot2")
library(ggplot2)

# Create the plot
# y = "mean_per_sub_mean"z
# combined_pca <- combined_pca_scores %>%
  # mutate(group_index = group_indices(., stim_ordered))

combined_pca <- combined_pca_scores %>%
  group_by(stim_ordered) %>%
  mutate(group_index = row_number())
ggplot(combined_pca, aes(x=group_index,y=PC2, group = stim_ordered, colour=stim_ordered)) +
  stat_smooth(method="loess", span=0.25, se=TRUE, aes(color=stim_ordered), alpha=0.3) +
  theme_bw()


```

### lmer per region
```{r}
# model.time <- lmer(tr_value ~ tr_ordered * stim_ordered  + (1 | roi/sub), data = df_long)
# 
# # model.time <- lmer(tr_value ~ tr_ordered * cue_ordered + (cue_ordered|sub), data=dfcue_long)
# summary(model.time)
# Assuming your data frame is named 'data_df' and 'value' is the column containing the values extracted from the regions.

# Load necessary packages
install.packages("lme4")   # Install the lme4 package if you haven't already
library(lme4)             # Load the lme4 package

# Create an empty vector to store corrected p-values for each region
corrected_p_values <- numeric()

anova_results_list <- list()
# Loop through each region
for (region in unique(df_long$roi)) {
  # Subset the data for the current region
  region_data <- subset(df_long, region == region)
  
  # Fit the mixed-effects model with region and subject as random effects
  model.time <- lmer(tr_value ~ tr_ordered * stim_ordered  + (1 | sub), data = region_data)
  aov.model.time <- anova(model.time)
  # Extract p-values for cue and time effects
  # p_values <- coef(summary(model))[, "Pr(>|t|)"][c("cuetype1", "time")]
  p_values <- aov.model.time$"Pr(>F)"
  labels <- rownames(aov.model.time)
  anova_results <- data.frame(Term = labels, P_Value = p_values)
  anova_results_list[[length(anova_results_list) + 1]] <- anova_results
  
  # Correct p-values for multiple comparisons (using Bonferroni method)
  corrected_p_values <- c(corrected_p_values, p.adjust(p_values, method = "bonferroni"))
}
combined_anova_results <- do.call(rbind, anova_results_list)

# Now you have the corrected p-values for each region, indicating significant cue or time effects.
# You can use these p-values to identify regions with significant effects based on a chosen significance level (e.g., 0.05).

```

```{r}
# Assuming you have a dataframe named 'data' containing the 20 data points, 'x' and 'y' values, and corresponding standard deviations 'sd'

# Load the ggplot2 library
# install.packages("ggplot2")
library(ggplot2)

# Create the plot
# y = "mean_per_sub_mean"z
ggplot(groupwise, aes(x=tr_ordered,y=mean_per_sub_mean, group = stim_ordered, colour=stim_ordered)) +
  stat_smooth(method="loess", span=0.25, se=TRUE, aes(color=stim_ordered), alpha=0.3) +
  theme_bw()

```
```{r}
# ggplot(data=groupwise, aes(x=tr_ordered, y=mean_per_sub_mean, ymin=se, ymax=se, fill=stim_ordered, linetype=stim_ordered)) + 
#  geom_line() + 
#  geom_ribbon(alpha=0.5)  
# Assuming you have a dataframe named 'data' containing the 20 mean data points and corresponding standard errors
# 'x' represents the x-values (e.g., time points)
# 'mean_y' represents the mean y-values
# 'se_y' represents the standard errors of the mean y-values

# Load the ggplot2 library
# install.packages("ggplot2")
library(ggplot2)
# groupwise$x <- as.numeric(groupwise$x)
# 
# # Sort the dataframe by the 'x' variable (if it's not already sorted)
# data <- data[order(data$x), ]

# Create the plot
# Create the plot with custom span and smoothing method
ggplot(groupwise, aes(x=tr_ordered,y=mean_per_sub_mean)) +
  geom_line() +                                   # Plot the smooth line for the mean
  geom_ribbon(aes(ymin = mean_per_sub_mean - se, ymax = mean_per_sub_mean + se), alpha = 0.3) + # Add the ribbon for standard error
  geom_smooth(method = "loess", span = 0.1, se = FALSE) +       # Add the loess smoothing curve
  labs(x = "X-axis Label", y = "Y-axis Label", title = "Smooth Line with Standard Error Ribbon") +
  theme_minimal()

```



## epoch: stim, high cue vs low cue
```{r}
# ------------------------------------------------------------------------------
#                       epoch stim, high cue vs low cue
# ------------------------------------------------------------------------------
# --------------------- subset regions based on ROI ----------------------------

# datadir = "/Volumes/spacetop_projects_cue/analysis/fmri/spm/fir/ttl1"
# taskname = "pain"
# exclude <- "sub-0001"
# filename <- paste0("sub-*_runtype-", taskname, "*roi-MT_tr-42.csv")
#   common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
#   ))
#   filter_path <- common_path[!str_detect(common_path, pattern = exclude)]
# 
# df <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
#     read.table(files, header = TRUE, sep = ",")
#     }))


parsed_df <- df %>%
  separate(condition, into = c("cue", "stim"), sep = "_", remove = FALSE)

TR_length <- 42

df_long <- pivot_longer(parsed_df, cols = starts_with("tr"), names_to = "tr_num", values_to = "tr_value")

# ----------------------------- clean factor -----------------------------------
df_long$tr_ordered <- factor(
        df_long$tr_num,
        levels = c(paste0("tr", 1:TR_length))
    )
df_long$cue_ordered <- factor(
        df_long$cue,
        levels = c("cueH", "cueL")
    )

# --------------------------- summary statistics -------------------------------
subjectwise <- meanSummary(df_long,
                                      c("sub", "tr_ordered", "cue_ordered"), "tr_value")
groupwise <- summarySEwithin(
  data = subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c("cue_ordered", "tr_ordered"),
  idvar = "sub"
)
groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

# --------------------------------- plot ---------------------------------------
LINEIV1 = "tr_ordered"
LINEIV2 = "cue_ordered"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
sorted_indices <- order(groupwise$tr_ordered)
groupwise_sorted <- groupwise[sorted_indices, ]
p2 = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Epoch: stimulus, High cue vs. Low cue", ggtitle="time_series", color=c("red","blue"))
time_points <- seq(1, 0.46 * TR_length, 0.46)
p2 + scale_x_discrete(labels = setNames(time_points, colnames(df_long)[7:7+TR_length]))+ theme_classic()
p2 + theme_classic()
```



## epoch: 6 cond
```{r}
# ------------------------------------------------------------------------------
#                       epoch stim, high cue vs low cue
# ------------------------------------------------------------------------------
# --------------------- subset regions based on ROI ----------------------------

# ----------------------------- clean factor -----------------------------------
df_long$tr_ordered <- factor(
        df_long$tr_num,
        levels = c(paste0("tr", 1:TR_length))
    )
df_long$cue_ordered <- factor(
        df_long$cue,
        levels = c("cueH", "cueL")
    )
df_long$stim_ordered <- factor(
        df_long$stim,
        levels = c("stimH", "stimM", "stimL")
    )

df_long$sixcond <- factor(
        df_long$condition,
        levels = c("cueH_stimH", "cueL_stimH", 
                   "cueH_stimM", "cueL_stimM",
                   "cueH_stimL", "cueL_stimL")
) 
# --------------------------- summary statistics -------------------------------
subjectwise <- meanSummary(df_long,
                                      c("sub", "tr_ordered", "sixcond"), "tr_value")
groupwise <- summarySEwithin(
  data = subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c("sixcond", "tr_ordered"),
  idvar = "sub"
)
groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

# --------------------------------- plot ---------------------------------------
LINEIV1 = "tr_ordered"
LINEIV2 = "sixcond"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
sorted_indices <- order(groupwise$tr_ordered)
groupwise_sorted <- groupwise[sorted_indices, ]
p3H = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Epoch: stimulus, High cue vs. Low cue", ggtitle="time_series", color=c("#5f0f40","red","gray", "gray", "gray", "gray"))
time_points <- seq(1, 0.46 * TR_length, 0.46)
p3H + scale_x_discrete(labels = setNames(time_points, colnames(df_long)[7:7+TR_length]))+ theme_classic()
p3H + theme_classic()
```

```{r}
p3M = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Epoch: stimulus, High cue vs. Low cue", ggtitle="time_series", color=c("#d6d6d6","#d6d6d6","#bc3908", "#f6aa1c", "gray", "gray"))
time_points <- seq(1, 0.46 * TR_length, 0.46)
p3M + scale_x_discrete(labels = setNames(time_points, colnames(df_long)[7:7+TR_length]))+ theme_classic()
p3M + theme_classic()
```

```{r}
p3L = plot_timeseries(groupwise, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Epoch: stimulus, High cue vs. Low cue", ggtitle="time_series", color=c("gray","gray","gray", "gray", "#2541b2", "#00a6fb"))
time_points <- seq(1, 0.46 * TR_length, 0.46)
p3L + scale_x_discrete(labels = setNames(time_points, colnames(df_long)[7:7+TR_length]))+ theme_classic()
p3L + theme_classic()
```



## epoch: cue, high cue vs low cue
```{r}
# ------------------------------------------------------------------------------
#                       epoch cue, high cue vs low cue
# ------------------------------------------------------------------------------

# load dataframes
taskname = "pain"
exclude <- "sub-0001"

filename <- paste0("fir-beta_roi-glasser_task-", taskname, "*_epoch-cue_cond-cueL_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

lowcue.epochcuedf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))

lowcue.epochcuedf$cue <- "low_cue"

filename <- paste0("fir-beta_roi-glasser_task-", taskname, "*_epoch-cue_cond-cueH_delay-20.tsv")
  common_path <- Sys.glob(file.path(datadir, "sub-*",  filename
  ))
  filter_path <- common_path[!str_detect(common_path, pattern = exclude)]

highcue.epochcuedf <- do.call("rbind.fill", lapply(filter_path, FUN = function(files) {
    read.table(files, header = TRUE, sep = "\t")
    }))
highcue.epochcuedf$cue <- "high_cue"

# concatenate dataframes
dfcue.epochcue <- rbind(highcue.epochcuedf, lowcue.epochcuedf)
dfcue.epochcue_long <- pivot_longer(dfcue.epochcue, cols = starts_with("tr_"), names_to = "tr_num", values_to = "tr_value")

# ----------------------------- clean factor -----------------------------------
# we want to order the levels so that they make sense in the plots
dfcue.epochcue_long$tr_ordered <- factor(
        dfcue.epochcue_long$tr_num,
        levels = c(paste0("tr_", 0:19))
    )
dfcue.epochcue_long$cue_ordered <- factor(
        dfcue.epochcue_long$cue,
        levels = c("high_cue", "low_cue")
    )

# --------------------------- summary statistics -------------------------------
subjectwise.cue.epochcue <- meanSummary(dfcue.epochcue_long,
                                      c("sub", "tr_ordered", "cue_ordered"), "tr_value")
groupwise.cue.epochcue <- summarySEwithin(
  data = subjectwise.cue.epochcue,
  measurevar = "mean_per_sub",
  withinvars = c("cue_ordered", "tr_ordered"),
  idvar = "sub"
)
groupwise.cue.epochcue$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402
```


```{r}
# --------------------------------- plot ---------------------------------------
LINEIV1 = "tr_ordered"
LINEIV2 = "cue_ordered"
MEAN = "mean_per_sub_norm_mean"
ERROR = "se"
dv_keyword = "actual"
sorted_indices <- order(groupwise.cue.epochcue$tr_ordered)
groupwise.cue.epochcue_sorted <- groupwise.cue.epochcue[sorted_indices, ]
p3 = plot_timeseries(groupwise.cue.epochcue_sorted, 
               LINEIV1, LINEIV2, MEAN, ERROR,  xlab = "Runs" , ylab= "Beta coefficients", ggtitle="time_series", color=c("red", "blue"))
time_points <- seq(0, 0.46 * 19, 0.46)
p3 + scale_x_discrete(labels = setNames(time_points, colnames(df)[4:23]))+ theme_classic() 
p3 +  theme_classic() 
```

### PCA subjectwise
```{r}
# install.packages("ggplot2")    # Install ggplot2 if you haven't already
# install.packages("FactoMineR") # Install FactoMineR if you haven't already
library(ggplot2)
library(FactoMineR)



# Assuming your original dataframe is named 'df'

# Convert the dataframe to wide format
# df_wide <- pivot_wider(subjectwise.cue.epochcue, 
#                        id_cols = c("tr_ordered", "cue_ordered"), 
#                        names_from = "sub", 
#                        values_from = "mean_per_sub")

df_wide <- pivot_wider(subjectwise.cue.epochcue, 
                       id_cols = c("sub", "cue_ordered"), 
                       names_from = "tr_ordered", 
                       values_from = "mean_per_sub")
cue.epochcue.high <- df_wide[df_wide$cue_ordered == "high_cue",]
cue.epochcue.low <- df_wide[df_wide$cue_ordered == "low_cue",]
# selected_columns <- subset(stim_high.df, select = 2:(ncol(stim_high.df) - 1))
meancue.epochcue.high <- data.frame(subset(cue.epochcue.high, select = 3:(ncol(cue.epochcue.high) )))
cuehigh.epochcue.pca_result <- prcomp(meancue.epochcue.high)
cuehigh.epochcue.pca_scores <- as.data.frame(cuehigh.epochcue.pca_result$x)
cuehigh.epochcue.variance_explained <- cuehigh.epochcue.pca_result$sdev^2 / sum(cuehigh.epochcue.pca_result$sdev^2)
cuehigh.epochcue.stdev <- cuehigh.epochcue.pca_result$sdev
plot(cuehigh.epochcue.variance_explained)


meancue.epochcue.low <- data.frame(subset(cue.epochcue.low, select = 3:(ncol(cue.epochcue.low) )))
cuelow.epochcue.pca_result <- prcomp(meancue.epochcue.low)
cuelow.epochcue.pca_scores <- as.data.frame(cuelow.epochcue.pca_result$x)
cuelow.epochcue.variance_explained <- cuelow.epochcue.pca_result$sdev^2 / sum(cuelow.epochcue.pca_result$sdev^2)
cuelow.epochcue.stdev <- cuelow.epochcue.pca_result$sdev
library(plotly)  # You can use plotly to create an interactive 3D plot

combined.cue.epochcue.pca_scores <- rbind(cuehigh.epochcue.pca_scores, cuelow.epochcue.pca_scores)

# Add a new column to indicate the cue_ordered category (high_stim or low_stim)
combined.cue.epochcue.pca_scores$cue_ordered <- c(rep("high_stim", nrow(cuehigh.epochcue.pca_scores)), rep("low_stim", nrow(cuelow.epochcue.pca_scores)))

# Create the 3D PCA plot
plot_ly(combined.cue.epochcue.pca_scores, x = ~PC1, y = ~PC2, z = ~PC3, type = "scatter3d", mode = "markers",
        color = ~cue_ordered)
# data_matrix <- groupwise[groupwise$cue_ordered == "high_stim",c("tr_ordered", "mean_per_sub_norm_mean")]
# sorted_indices <- order(data_matrix$tr_ordered)
# df_ordered <- data_matrix[sorted_indices, ]
# pca_result <- PCA(data_matrix$mean_per_sub_norm_mean)
# datapoints <- df$datapoints
```

```{r}
# combined.cue.epochcue.pca_scores
# average_scores <- colMeans(combined.cue.epochcue.pca_scores)

average_scores_per_condition <- combined.cue.epochcue.pca_scores %>%
  group_by(cue_ordered) %>%
  summarise(across(everything(), mean))
# pca_plot_data <- data.frame(PC = 1:20, Average_Score = average_scores)
# Combine PC columns into a long format using pivot_longer
library(tidyr)

pca_data_long <- average_scores_per_condition %>%
  pivot_longer(cols = starts_with("PC"), names_to = "Principal_Component", values_to = "Score")

# Plot all principal components using facets
# ggplot(pca_data_long, aes(x = Principal_Component, group = cue_ordered, y = Score)) +
#   geom_point() 
#   # facet_wrap(~ Principal_Component, scales = "free_y", ncol = 4) +
#   # labs(x = "Cue Ordered", y = "Principal Component Score", title = "PCA Scores vs. Cue Ordered")

ggplot(pca_data_long, aes(x = Principal_Component, y = Score, color = cue_ordered)) +
  geom_point() +
  labs(x = "Principal Component", y = "Score", title = "PCA Scores vs. Principal Component") +
  theme_minimal()

```
