# [physio] SCL {#ch92_SCL}
---
title: "92_SCL_beta"
output: html_document
date: "2023-07-20"
---

## Outline
### load data
### subjectwise, groupwise mean

```{r message=TRUE, warning=TRUE, include=FALSE}
library(car)
library(psych)
library(reshape)
library(plyr); library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
main_dir = dirname(dirname(getwd()))
file.sources = list.files(file.path(main_dir, "scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```

```{r function::simple_contrasts_singletrial, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
simple_contrasts_singletrial <- function(df) {
# [ CONTRASTS ]  ________________________________________________________________________________ # nolint
# contrast code ________________________________________
df$stim_factor <- factor(df$stim_type)

# contrast code 1 linear
df$STIM_linear[df$stim_type == "low_stim"] <-  -0.5
df$STIM_linear[df$stim_type == "med_stim"] <-  0
df$STIM_linear[df$stim_type == "high_stim"] <-  0.5

# contrast code 2 quadratic
df$STIM_quadratic[df$stim_type == "low_stim"] <-  -0.33
df$STIM_quadratic[df$stim_type == "med_stim"] <-  0.66
df$STIM_quadratic[df$stim_type == "high_stim"] <-  -0.33

df$stim_name[df$stim_type == "intercept"] <- "intercept"
df$stim_name[df$stim_type == "low_stim"] <- "low"
df$stim_name[df$stim_type == "med_stim"] <- "med"
df$stim_name[df$stim_type == "high_stim"] <- "high"

df$stim_ordered <- factor(
        df$stim_name,
        levels = c("intercept", "low", "med", "high")
    )

return(df)
}
```

```{r}
beta <- read.table(file = "/Volumes/spacetop_projects_cue/analysis/physio/glm/pmod-stimintensity/glm-pmodintenisy_task-pain_scr.tsv", sep = '\t', header = TRUE)

```
```{r}
beta_long <- gather(beta, key = "stim_type", value = "scl_value", intercept, low_stim, med_stim, high_stim)
beta_con <- simple_contrasts_singletrial(beta_long)

```


```{r}

# ----------------------------------------------------------------------
#                     summary statistics for plots
# ----------------------------------------------------------------------
subject <- "sub"
model_iv <- "stim_ordered"
dv <- "scl_value"
taskname <- "pain"
dv_keyword <- "SCL"
analysis_dir <- file.path(main_dir, "analysis", "mixedeffect", "model92_iv-stim_dv-sclbeta", as.character(Sys.Date()))
# model_iv2 <- "cue_ordered"


# ======= NOTE: calculate mean and se ----------------------------------
SCLstim_subjectwise <- meanSummary(beta_con,
                                      c(subject, model_iv), dv)
SCLstim_groupwise <- summarySEwithin(
  data = SCLstim_subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv),
  idvar = subject
)
SCLstim_groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

# combined_se_calc_cooksd <-NPSstimcue_groupwise
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub"
ggtitle <- paste(taskname, " - ", dv, "Cooksd removed")
title <- paste(taskname, " - ", dv)
xlab <- ""
ylab <- "ROI average activation (A.U)"
ylim <- c(-10, 60)

if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4575B4", "#D73027")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_task-", taskname, "_rating-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                            raincloudplots
# ----------------------------------------------------------------------

# combined_se_calc_cooksd <-NPSstimcue_groupwise
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub"
ggtitle <- paste( dv)
title <- paste( dv)
xlab <- ""
ylab <- "SCL beta coefficients (A.U.)"

dv_keyword <- "fdmean"
if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("gray", "#1B9E77", "#D95F02", "red")
} else {
  color <- c("gray", "#1B9E77", "#D95F02", "red")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_qc-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                            raincloudplots
# ----------------------------------------------------------------------
# TODO: 
# * change the range of the figure
# * change the x-axis
# * drop the NA conditions
# * change theme
# * adjust the box plots

ylim <- c(-2, 2)
taskname = "all"
w <- 10; h <- 5
g <- plot_halfrainclouds_onefactor(
  SCLstim_subjectwise,
  SCLstim_groupwise,
  model_iv,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g <- g + theme_bw() + theme_classic()
print(g)
SCLstim_groupwise$task = "pain"

k <- plot_lineplot_onefactorthick(SCLstim_groupwise,
                             taskname = "pain",
                        iv = "stim_ordered",
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c("intercept" = "gray",
                                  "high" = "red",
                                  "med" = "orange",
                                  "low" = "blue"), 
                        ggtitle = title, 
                        xlab = "Stimulus intensity", ylab = "ROI average activation (A.U.)")
k <- k + theme(aspect.ratio=.8)
print(k)
```







