---
title: "fdmean"
output: html_document
date: "2023-07-18"
---

```{r}
library(car)
library(psych)
library(reshape)
library(PupillometryR)
library(plyr); library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
file.sources = list.files(c("/Users/h/Documents/projects_local/cue_expectancy/scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```


```{r}
# load in the dataframe
# create contrasts for pain vs non-pain runs
# summary statistics for each subject
# group wise statistics
# plot
```


```{r}
# df <- read.csv("/Users/h/Documents/summer/summer_RA/fdmean_run_type.tsv")
fdmeandf <- read.table(file = "/Users/h/Documents/summer/summer_RA/fdmean_run_type.tsv", sep = '\t', header = TRUE)

```

```{r}
# contrast code 1 linear

fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "pain"] <- 0.5
fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "vicarious"] <- -0.5
fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "cognitive"] <- -0.5
df <- fdmeandf %>% drop_na(PAIN_NOPAIN)
```

```{r}
df$sub_factor <- factor(df$sub)
model.fdmean <- lmer(fd_mean ~ PAIN_NOPAIN + (1|sub_factor), data=df)
```

```{r}
summary(model.fdmean)
```

```{r}
df$run_name[df$run_type == "pain"] <- "pain"
df$run_name[df$run_type == "vicarious"] <- "non-pain"
df$run_name[df$run_type == "cognitive"] <- "non-pain"

df$pain_ordered <- factor(
        df$run_name,
        levels = c("non-pain", "pain")
    )

subject <- "sub_factor"
model_iv <- "pain_ordered"
dv <- "fd_mean"
subjectwise <- meanSummary(df,c(subject, model_iv), dv)

groupwise <- summarySEwithin(
  data=subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv),
  idvar = subject
)
```

```{r}
analysis_dir <- "/Users/h/Desktop"
# combined_se_calc_cooksd <-NPSstimcue_groupwise
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub_factor"
ggtitle <- paste( dv)
title <- paste( dv)
xlab <- ""
ylab <- "FD mean (mm)"

dv_keyword <- "fdmean"
if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4575B4", "#D73027")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_qc-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                            raincloudplots
# ----------------------------------------------------------------------
# TODO: 
# * change the range of the figure
# * change the x-axis
# * drop the NA conditions
# * change theme
# * adjust the box plots

ylim <- c(0,.6)
taskname = "all"
w <- 10; h <- 5
g <- plot_halfrainclouds_onefactor(
  subjectwise,
  groupwise,
  model_iv,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g <- g + theme_bw() + theme_classic()
print(g)


k <- plot_lineplot_twofactor(NPSstimcue_groupwise,
                        iv1 = "stim_ordered", iv2 = "cue_ordered",
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c("pain" = "red",
                                  "non-pain" = "gray"))
                                  # "med" = "orange",

```

```{r}
df_example <- tibble(x = c(1,2,NA), y = c("a", NA, "b"))
df_example %>% drop_na(x)
```

