# [fMRI] ROI ~ decoding {#ROI_decoding}

## What is the purpose of this notebook? {.unlisted .unnumbered}

```{r libraries_SIIPS_stim, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(car)
library(lme4)
library(optimx)
library(minqa)
library(dfoptim)
library(tidyverse)
library(psych)
library(reshape)
library(dplyr)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
library(plyr)
library(ggpubr)
library(r2mlm)
library(effectsize)
# library(devtools)
options(es.use_symbols = TRUE) # get nice symbols when printing! (On Windows, requires R >= 4.2.0)
library(EMAtools)
library(emmeans)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(plotly)
library(DT)
library(scico)
library(cueR)
library(raincloudplots)
# devtools::source_url("https://raw.githubusercontent.com/RainCloudPlots/RainCloudPlots/master/tutorial_R/R_rainclouds.R")
# devtools::source_url("https://raw.githubusercontent.com/RainCloudPlots/RainCloudPlots/master/tutorial_R/summarySE.R")

devtools::source_url("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
library(r2mlm)
main_dir <- dirname(dirname(getwd()))
file.sources = list.files(file.path(main_dir, 'scripts', 'step02_R', 'utils'),
                          pattern="*.R",
                          full.names=TRUE,
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)

```

## function

```{r}
load_process_BOLD_data <- function(data_dir, roi_name) {
  # File paths
  lowBOLD_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-low_BOLD.tsv"))
  highBOLD_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-high_BOLD.tsv"))

  # Read data
  lowBOLDdf <- readr::read_tsv(lowBOLD_fname, show_col_types = FALSE)
  highBOLDdf <- readr::read_tsv(highBOLD_fname, show_col_types = FALSE)

  # Add cue labels
  # lowBOLDdf$cue <- "low cue"
  # highBOLDdf$cue <- "high cue"

  # Combine data
  bold_df <- rbind(lowBOLDdf, highBOLDdf)
  bold_df$stim_name <- NA; bold_df$cue_name <- NA;
  bold_df$stim <- factor(bold_df$stimulusintensity, levels = c("low", "med", "high"))
bold_df$stim_name[bold_df$stim == "high"] <-  "High stim"
bold_df$stim_name[bold_df$stim == "med"] <-  "Med stim"
bold_df$stim_name[bold_df$stim == "low"] <-  "Low stim"
bold_df$cue_name[bold_df$cuetype == "high"] <-  "High cue"
bold_df$cue_name[bold_df$cuetype == "low"] <-  "Low cue"

bold_df$stim_ordered <- factor(bold_df$stim_name,
                                   levels = c("Low stim", "Med stim", "High stim"))
bold_df$cue_ordered <- factor(bold_df$cue_name,
                                  levels = c("Low cue", "High cue"))


  # Calculate summary statistics
  subject <- "sub"
  iv1 <- "stim_ordered"
  iv2 <- "cue_ordered"
  dv <- grep("^mean_nps", names(bold_df), value = TRUE)

  bold_subjectwise <- meanSummary(bold_df, c(subject, iv1, iv2), dv)
  bold_groupwise <- summarySEwithin(
    data = bold_subjectwise,
    measurevar = "mean_per_sub",
    withinvars = c(iv1, iv2),
    idvar = subject
  )
  bold_groupwise$score <- "bold"

  return(bold_groupwise)
}



load_process_f1_data <- function(data_dir, roi_name) {
  # Construct file names
  low_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-low_f1score.tsv"))
  high_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-high_f1score.tsv"))

  # Load data and add cue labels
  lowdf <- readr::read_tsv(low_fname, show_col_types = FALSE)
  lowdf$cue <- "Low cue"
  highdf <- readr::read_tsv(high_fname, show_col_types = FALSE)
  highdf$cue <- "High cue"

  # Combine data
  df <- rbind(lowdf, highdf)

  # Pivot data from wide to long format
  df_long <- tidyr::pivot_longer(
    data = df,
    cols = starts_with("F1_"),
    names_to = "stim",
    values_to = "f1_value",
    names_prefix = "F1_"
  )

  # Adjust stimulus levels to meaningful labels
  df_long$stim <- factor(df_long$stim, levels = c("low", "med", "high"))
  # df_long$stim_name <- ifelse(df_long$stim == "high", "High", ifelse(df_long$stim == "med", "Med", "Low"))
  # bold_df$stim <- factor(bold_df$stimulusintensity, levels = c("low", "med", "high"))
  df_long$stim_name[df_long$stim == "high"] <-  "High stim"
  df_long$stim_name[df_long$stim == "med"] <-  "Med stim"
  df_long$stim_name[df_long$stim == "low"] <-  "Low stim"
  df_long$stim_ordered <- factor(df_long$stim_name, levels = c("Low stim", "Med stim", "High stim"))
  df_long$cue_ordered <- factor(df_long$cue, levels = c("Low cue", "High cue"))

  # Calculate summary statistics
  subject <- "sub"
  iv1 <- "stim_ordered"
  iv2 <- "cue_ordered"
  dv <- "f1_value"

  # Assuming meanSummary and summarySEwithin are defined functions or part of a loaded package
  f1_subjectwise <- meanSummary(df_long, c(subject, iv1, iv2), dv)
  f1_groupwise <- summarySEwithin(
    data = f1_subjectwise,
    measurevar = "mean_per_sub",
    withinvars = c(iv1, iv2),
    idvar = subject
  )
  f1_groupwise$score <- "f1"

  return(f1_groupwise)
}


load_process_acc_data <- function(data_dir, roi_name) {
  # Construct file names
  low_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-low_accuracy.tsv"))
  high_fname <- file.path(data_dir, paste0("roi-", roi_name, "_cue-high_accuracy.tsv"))

    # Load data and add cue labels
  lowdf <- readr::read_tsv(low_fname, show_col_types = FALSE)
  lowdf$cue <- "Low cue"
  highdf <- readr::read_tsv(high_fname, show_col_types = FALSE)
  highdf$cue <- "High cue"

  # Combine data
  df <- rbind(lowdf, highdf)

  # Pivot data from wide to long format
  df_long <- tidyr::pivot_longer(
    data = df,
    cols = starts_with("Accuracy_"),
    names_to = "stim",
    values_to = "accuracy",
    names_prefix = "Accuracy_"
  )


  # Adjust the stim levels from the column names to meaningful labels if necessary
  df_long$stim_name <- NA
  df_long$stim <- factor(df_long$stim, levels = c("low", "med", "high"))
  df_long$stim_name[df_long$stim == "high"] <-
    "High stim"
  df_long$stim_name[df_long$stim == "med"] <-
    "Med stim"
  df_long$stim_name[df_long$stim == "low"] <-
    "Low stim"

  df_long$stim_ordered <- factor(df_long$stim_name,
                                     levels = c("Low stim", "Med stim", "High stim"))
  df_long$cue_ordered <- factor(df_long$cue,
                                    levels = c("Low cue", "High cue"))
  #  summary statistics  _________________________________________________________
  subject <- "sub"
  iv1 <- "stim_ordered"
  iv2 <- "cue_ordered"
  dv <- "accuracy"
  acc_subjectwise <- meanSummary(df_long,
                                        c(subject, iv1, iv2), dv)
  acc_groupwise <- summarySEwithin(
    data = acc_subjectwise,
    measurevar = "mean_per_sub",
    withinvars = c(iv1, iv2),
    idvar = subject
  )

  acc_groupwise$score <- "acc"
  return(acc_groupwise)
}

calculate_best_offset <- function(data_bar, data_line, mean_bar, mean_line, error_bar, error_line) {
  # Find the top of the highest bar plot (including error)
  max_bar_with_error <- max(data_bar[[mean_bar]] + data_bar[[error_bar]], na.rm = TRUE)

  # Find the bottom of the lowest line plot (considering error)
  min_line_with_error <- min(data_line[[mean_line]] - data_line[[error_line]], na.rm = TRUE)

  # Calculate offset as the difference if bars go higher than lines, otherwise, set a default minimum offset
  if (max_bar_with_error > min_line_with_error) {
    offset <- max_bar_with_error - min_line_with_error
  } else {
    offset <- abs(min_line_with_error) * 0.1  # Default offset of 10% of the line range
  }

  # Adding a small buffer to ensure clear separation
  offset <- offset + abs(min_line_with_error) * 0.05

  return(offset)
}
####################################
#        plot combined
####################################
plot_combined <- function(data_bar, data_line, iv1, iv2, mean_bar, mean_line, error_bar, error_line, color_line, xlab, ylab_bar, ylab_line, offset, positiondodge, title) {
      bar_width <- 0.7  # Decrease this value to make bars narrower
    dodge_width <- 0.05  # Decrease this value to reduce space between bars within groups

    # Add the offset to line plot data for visual separation
    data_line$mean_line_adj <- data_line[[mean_line]] + offset
    data_line$ymin_adj <- data_line[[mean_line]] - data_line[[error_line]] + offset
    data_line$ymax_adj <- data_line[[mean_line]] + data_line[[error_line]] + offset

    # Create the ggplot object
    g <- ggplot() +
        # Bar plot for BOLD scores _____________________________________________
        geom_bar(data = data_bar, aes(x = .data[[iv1]], y = .data[[mean_bar]], fill = .data[[iv2]]), stat="identity", position=position_dodge(width = dodge_width), width=bar_width) +
        geom_errorbar(data = data_bar, aes(x = .data[[iv1]], ymin = .data[[mean_bar]] - .data[[error_bar]], ymax = .data[[mean_bar]] + .data[[error_bar]]), position=position_dodge(width = dodge_width), width=0.1) +
        # Adjusted line plot for f1 scores ______________________________________
        geom_line(data = data_line, aes(x = .data[[iv1]], y = mean_line_adj, group = .data[[iv2]], color = .data[[iv2]]), size = .5) +
        geom_point(data = data_line, aes(x = .data[[iv1]], y = mean_line_adj, color = .data[[iv2]]), size = 2, position=position_dodge(width = dodge_width)) +
        geom_errorbar(data = data_line, aes(x = .data[[iv1]], ymin = ymin_adj, ymax = ymax_adj, color = .data[[iv2]]), width=0.1, position=position_dodge(width = dodge_width)) +
        # Scales for fill and color ____________________________________________
        scale_fill_manual(values = color_line) +
        scale_color_manual(values = color_line) +
        # X and Y axis labels __________________________________________________
        xlab(xlab) +
        ylab(ylab_bar) +
        ggtitle(title) +
        # Primary y-axis for BOLD scores and Secondary y-axis for original f1 scores
        scale_y_continuous(
            name = ylab_bar,
            sec.axis = sec_axis(~ . - offset, name = ylab_line)  # Adjust the secondary axis labels to reflect original values
        ) +
        # Faceting to create separate panels for each cue_ordered level
        facet_wrap(~ .data[[iv2]], scales = "free_x") +
        # Theme adjustments ____________________________________________________
        theme_classic() +
        theme(
            axis.text.x = element_text(angle = 90, hjust = 1),
            axis.title.y.right = element_text(color = "black", angle = 270),
            strip.background = element_blank(),
            legend.position = "bottom",
            aspect.ratio = 1.4
        )

    return(g)
}

```

```{r}
data_dir = "/Users/h/Documents/projects_local/cue_expectancy/analysis/fmri/nilearn/deriv04_NPSdecoding"
# roi_name <- "npspos_rdpIns"  # Replace with your actual ROI name
roi_list <- c( "npsneg_rIPL")
#,"npsneg_pgACC","npsneg_rLOC", "npsneg_lLOC",
#            "npspos_dACC", "npspos_rdpIns", "npspos_rS2_Op", "npspos_rV1", "npspos_vermis")
roi_title <- c( "IPL (R)",  "pgACC","LOC (R)", "LOC (L)",
            "dACC", "dpIns (R)", "S2 & Op (R)", "V1 (R)", "Vermis")

for (i in seq_along(roi_list)) {
  roi_name <- roi_list[i]
  dv_title <- roi_title[i]

# for (roi_name in roi_list) {
bold_data <- load_process_BOLD_data(data_dir, roi_name)
f1_data <- load_process_f1_data(data_dir, roi_name)
# Define an offset for visual separation
# offset_value <- 0.3

offset_value <- calculate_best_offset(data_bar=bold_data, data_line=f1_data, mean_bar="mean_per_sub_mean", mean_line="mean_per_sub_mean", error_bar="se", "se")
# Example usage
combined_plot <- plot_combined(
    data_bar = bold_data,#bold_groupwise,
    data_line = f1_data, #f1_groupwise,
    iv1 = "stim_ordered",
    iv2 = "cue_ordered",
    mean_bar = "mean_per_sub_mean",
    mean_line = "mean_per_sub_mean",
    error_bar = "se",
    error_line = "se",
    color_line = c("Low cue" = "#3E61EC", "High cue" = "#FF0000"),
    xlab = "Stimulus Intensity",
    ylab_bar = "BOLD (a.u.)",
    ylab_line = "Classification (f1)",
    title = dv_title,
    offset = offset_value  # The offset for visual separation
)
combined_plot <- combined_plot + theme(aspect.ratio=1.3,
          text = element_text(size = 12), # Default text size for the plot
          axis.title = element_text(size = 12, ), # Axis titles
          axis.text = element_text(size = 10), # Axis text (x and y)
          plot.title = element_text(size = 15, hjust = 0.5), # Plot title
         axis.text.x = element_text(angle = 45, hjust = 1)
          )
print(combined_plot)
ggsave(paste0("/Users/h/Documents/projects_local/cue_expectancy/analysis/fmri/nilearn/deriv04_NPSdecoding/boldf1-", roi_name, ".svg"), combined_plot, width = 8, height = 4, dpi=300)
}
```

```{r}
data_dir = "/Users/h/Documents/projects_local/cue_expectancy/analysis/fmri/nilearn/deriv04_NPSdecoding"
# roi_name <- "npspos_rdpIns"  # Replace with your actual ROI name
roi_list <- c( "npsneg_rIPL", "npsneg_pgACC","npsneg_rLOC", "npsneg_lLOC",
           "npspos_dACC", "npspos_rdpIns", "npspos_rS2_Op", "npspos_rV1", "npspos_vermis")
roi_title <- c( "IPL (R)",  "pgACC","LOC (R)", "LOC (L)",
            "dACC", "dpIns (R)", "S2 & Op (R)", "V1 (R)", "Vermis")

for (i in 1) {#seq_along(roi_list)) {
  roi_name <- roi_list[i]
  dv_title <- roi_title[i]

# for (roi_name in roi_list) {
bold_data <- load_process_BOLD_data(data_dir, roi_name)
f1_data <- load_process_f1_data(data_dir, roi_name)
acc_data <- load_process_acc_data(data_dir, roi_name)
# Define an offset for visual separation
# offset_value <- 0.3

offset_value <- calculate_best_offset(data_bar=bold_data, data_line=acc_data, mean_bar="mean_per_sub_mean", mean_line="mean_per_sub_mean", error_bar="se", "se")
# Example usage
combined_plot <- plot_combined(
    data_bar = bold_data,#bold_groupwise,
    data_line = acc_data, #f1_groupwise,
    iv1 = "cue_ordered",
    iv2 = "stim_ordered",
    mean_bar = "mean_per_sub_mean",
    mean_line = "mean_per_sub_mean",
    error_bar = "se",
    error_line = "se",
    color_line = c("High stim" = "#9c0f5f", "Med stim" = "#c91b26", "Low stim" = "#FF8800"),
    xlab = "Stimulus Intensity",
    ylab_bar = "BOLD (a.u.)",
    ylab_line = "Classification (f1)",
    title = dv_title,
    offset = 0.000001  # The offset for visual separation
)
combined_plot <- combined_plot + theme(aspect.ratio=1.3,
          text = element_text(size = 12), # Default text size for the plot
          axis.title = element_text(size = 12, ), # Axis titles
          axis.text = element_text(size = 10), # Axis text (x and y)
          plot.title = element_text(size = 15, hjust = 0.5), # Plot title
         axis.text.x = element_text(angle = 45, hjust = 1)
          )
print(combined_plot)
ggsave(paste0("/Users/h/Documents/projects_local/cue_expectancy/analysis/fmri/nilearn/deriv04_NPSdecoding/boldf1-", roi_name, "_perstim.svg"), combined_plot, width = 8, height = 4, dpi=300)
}
```

## accuracy {.unlisted .unnumbered}

```{r}
data_dir = "/Users/h/Documents/projects_local/cue_expectancy/analysis/fmri/nilearn/deriv04_NPSdecoding"
# load data ____________________________________________________________________
low_fname <- file.path(data_dir, "roi-npspos_dACC_cue-low_accuracy.tsv") #roi-npspos_dACC_cue-high_cue
lowdf <- readr::read_tsv(low_fname)
lowdf$cue <- "low cue"
high_fname <- file.path(data_dir, "roi-npspos_dACC_cue-high_accuracy.tsv")
highdf <- readr::read_tsv(high_fname)
highdf$cue <- "high cue"
df <- rbind(lowdf, highdf)


# pivot wide to long ___________________________________________________________
df_long <- pivot_longer(
  data = df,
  cols = c(Accuracy_high, Accuracy_med, Accuracy_low),
  names_to = "stim",
  values_to = "accuracy",
  names_prefix = "Accuracy_"
)

# Adjust the stim levels from the column names to meaningful labels if necessary
df_long$stim <- factor(df_long$stim, levels = c("low", "med", "high"))
df_long$stim_name[df_long$stim == "high"] <-
  "High"
df_long$stim_name[df_long$stim == "med"] <-
  "Med"
df_long$stim_name[df_long$stim == "low"] <-
  "Low"

df_long$stim_ordered <- factor(df_long$stim_name,
                                   levels = c("Low", "Med", "High"))
df_long$cue_ordered <- factor(df_long$cue,
                                  levels = c("low cue", "high cue"))
#  summary statistics  _________________________________________________________
subject <- "sub"
iv1 <- "stim_ordered"
iv2 <- "cue_ordered"
dv <- "accuracy"
acc_subjectwise <- meanSummary(df_long,
                                      c(subject, iv1, iv2), dv)
acc_groupwise <- summarySEwithin(
  data = acc_subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(iv1, iv2),
  idvar = subject
)

acc_groupwise$score <- "acc"
# plot line plots ______________________________________________________________
g <- plot_lineplot_twofactor(acc_groupwise,# taskname = "pain",
                        iv1 = "stim_ordered", iv2 = "cue_ordered",
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c( "low cue" = "#3E61EC"),
                        ggtitle = "Decoding dACC",
                        xlab = "Stimulus intensity", ylab = "Accuracy")
g + theme(aspect.ratio=.8,
          text = element_text(size = 18), # Default text size for the plot
          axis.title = element_text(size = 24, ), # Axis titles
          axis.text = element_text(size = 18), # Axis text (x and y)
          plot.title = element_text(size = 24, hjust = 0.5) # Plot title
          ) +
  geom_line(size = 1) + # Adjust line thickness
  geom_point(size = 3)  # Adjust point size
```
