# [QC] SCL {#ch100_white matter csf}
---
title: "whitematter_csf"
output: html_document
date: "2023-07-28"
---

```{r include=FALSE}
library(car)
library(psych)
library(reshape)
library(plyr); library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
main_dir = dirname(dirname(getwd()))
file.sources = list.files(file.path(main_dir, "scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```

```{r}

# parameters
main_dir <- dirname(dirname(getwd()))
analysis_folder  = paste0("model96_iv-cue-stim_dv-nuissance")
analysis_dir <-
  file.path(main_dir,
            "analysis",
            "mixedeffect",
            analysis_folder,
            as.character(Sys.Date())) # nolint
dir.create(analysis_dir,
           showWarnings = FALSE,
           recursive = TRUE)
savedir <- analysis_dir
```

## load data
```{r}
df <- read.csv(file.path(main_dir, 'scripts/step10_nilearn/whitematter_csf/whitematter_csf_pain.csv' ))
```

```{r}
myData <- separate(df, fname, into = c("sub", "ses", "run", "runtype","event", "trial", "cuetype", "stimintensity"), sep = "_", remove = FALSE)
myData$sub <- sub("_.*", "", myData$sub)
myData$ses <- sub("_.*", "", myData$ses)
myData$run <- sub("_.*", "", myData$run)
myData$runtype <- str_extract(myData$runtype, "(?<=runtype-).*")
myData$event <- sub("_.*", "", myData$event)
myData$trial <- sub("_.*", "", myData$trial)
myData$cue <- str_extract(myData$cuetype, "(?<=cuetype-).*")
myData$stim <- str_extract(myData$stimintensity, "(?<=stimintensity-)[^.]+")
```

## whitematter

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
combined_se_calc_cooksd <- data.frame()
combined_psig <- data.frame()
taskname = "pain"
ggtitle <- paste(taskname, " - NPS (degree)")
title <- paste(taskname, " - outcome")
subject <- "sub"
w <- 10
h <- 6
dv_keyword <- "whitematter"

data <- myData

# [ CONTRASTS ]  ________________________________________________________________________________ # nolint
# contrast code ________________________________________
# data$stim[data$stim == "low"] <-  -0.5 # social influence task
# data$stim[data$stim == "med"] <- 0 # no influence task
# data$stim[data$stim == "high"] <-  0.5 # no influence task

data$STIM <- factor(data$stim)

# contrast code 1 linear
data$STIM_linear[data$stim == "low"] <- -0.5
data$STIM_linear[data$stim == "med"] <- 0
data$STIM_linear[data$stim == "high"] <- 0.5

# contrast code 2 quadratic
data$STIM_quadratic[data$stim == "low"] <- -0.33
data$STIM_quadratic[data$stim == "med"] <- 0.66
data$STIM_quadratic[data$stim == "high"] <- -0.33

# social cude contrast
data$CUE_high_gt_low[data$cuetype == "cuetype-low"] <-  -0.5 # social influence task
data$CUE_high_gt_low[data$cuetype == "cuetype-high"] <-  0.5 # no influence task

# data$EXPECT <- data$event02_expect_angle
# data <- data %>%
# mutate(NPS_gmc = NPSpos - mean(NPSpos))
#######################
stim_con1 <- "STIM_linear"
stim_con2 <- "STIM_quadratic"
iv1 <- "CUE_high_gt_low"
dv <- "whitematter"
#######################

# [ MODEL ] _________________________________________________ # nolint
model_savefname <- file.path(
  analysis_dir,
  paste(
    "lmer_task-",
    taskname,
    "_rating-",
    dv_keyword,
    "_",
    as.character(Sys.Date()),
    "_cooksd.txt",
    sep = ""
  )
)

cooksd <- lmer_twofactor_cooksd_fix(
  data,
  taskname,
  iv1,
  stim_con1,
  stim_con2,
  dv,
  subject,
  dv_keyword,
  model_savefname,
  'random_intercept',
  print_lmer_output = FALSE
)
influential <- as.numeric(names(cooksd)[(cooksd > (4 / as.numeric(length(unique(
  data$sub
)))))])
data_screen <- data[-influential,]

data_screen %>%
  group_by

# [ PLOT ] reordering for plots _________________________ # nolint
data_screen$cue_name[data_screen$cuetype == "cuetype-high"] <-
  "high cue"
data_screen$cue_name[data_screen$cuetype == "cuetype-low"] <-
  "low cue"

data_screen$stim_name[data_screen$stim == "high"] <-
  "high"
data_screen$stim_name[data_screen$stim == "med"] <-
  "med"
data_screen$stim_name[data_screen$stim == "low"] <-
  "low"

# DATA$levels_ordered <- factor(DATA$param_stimulus_type, levels=c("low", "med", "high"))

data_screen$stim_ordered <- factor(data_screen$stim_name,
                                   levels = c("low", "med", "high"))
data_screen$cue_ordered <- factor(data_screen$cue_name,
                                  levels = c("low cue", "high cue"))
model_iv1 <- "stim_ordered"
model_iv2 <- "cue_ordered"

#  [ PLOT ] calculate mean and se  _________________________
NPSstimcue_subjectwise <- meanSummary(data_screen,
                                      c(subject, model_iv1, model_iv2), dv)
NPSstimcue_groupwise <- summarySEwithin(
  data = NPSstimcue_subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv1, model_iv2),
  idvar = subject
)
NPSstimcue_groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

combined_se_calc_cooksd <-
  rbind(combined_se_calc_cooksd, NPSstimcue_groupwise)
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub"
ggtitle <- paste(taskname, " - NPSpos Cooksd removed")
title <- paste(taskname, " - NPSpos")
xlab <- ""
ylab <- "NPSpos (degree)"
ylim <- c(-10, 60)
dv_keyword <- "NPSpos"
if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4575B4", "#D73027")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_task-", taskname, "_rating-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)
g <- plot_halfrainclouds_twofactor(
  NPSstimcue_subjectwise,
  NPSstimcue_groupwise,
  model_iv1,
  model_iv2,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g
```

```{r echo=FALSE, warning=FALSE}
g <- plot_lineplot_twofactor_subsetthick(NPSstimcue_groupwise, taskname = "pain", 
                        iv1 = "stim_ordered", iv2 = "cue_ordered", 
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c("low cue" = "#5D5C5C","high cue" = "#D73027"), ggtitle = "Within pain task: whitematter as a function of stimulus intensity level and cue", 
                        xlab = "Stimulus intensity", ylab = "Average activation (A.U.)")
g + theme(aspect.ratio=.8)
```

## CSF


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
combined_se_calc_cooksd <- data.frame()
combined_psig <- data.frame()
taskname = "pain"
ggtitle <- paste(taskname, " - NPS (degree)")
title <- paste(taskname, " - outcome")
subject <- "sub"
w <- 10
h <- 6

data <- myData

# [ CONTRASTS ]  ________________________________________________________________________________ # nolint
# contrast code ________________________________________
# data$stim[data$stim == "low"] <-  -0.5 # social influence task
# data$stim[data$stim == "med"] <- 0 # no influence task
# data$stim[data$stim == "high"] <-  0.5 # no influence task

data$STIM <- factor(data$stim)

# contrast code 1 linear
data$STIM_linear[data$stim == "low"] <- -0.5
data$STIM_linear[data$stim == "med"] <- 0
data$STIM_linear[data$stim == "high"] <- 0.5

# contrast code 2 quadratic
data$STIM_quadratic[data$stim == "low"] <- -0.33
data$STIM_quadratic[data$stim == "med"] <- 0.66
data$STIM_quadratic[data$stim == "high"] <- -0.33

# social cude contrast
data$CUE_high_gt_low[data$cuetype == "cuetype-low"] <-  -0.5 # social influence task
data$CUE_high_gt_low[data$cuetype == "cuetype-high"] <-  0.5 # no influence task

# data$EXPECT <- data$event02_expect_angle
# data <- data %>%
# mutate(NPS_gmc = NPSpos - mean(NPSpos))
#######################
stim_con1 <- "STIM_linear"
stim_con2 <- "STIM_quadratic"
iv1 <- "CUE_high_gt_low"
dv <- "csf"
#######################

# [ MODEL ] _________________________________________________ # nolint
model_savefname <- file.path(
  analysis_dir,
  paste(
    "lmer_task-",
    taskname,
    "_rating-",
    dv_keyword,
    "_",
    as.character(Sys.Date()),
    "_cooksd.txt",
    sep = ""
  )
)

cooksd <- lmer_twofactor_cooksd_fix(
  data,
  taskname,
  iv1,
  stim_con1,
  stim_con2,
  dv,
  subject,
  dv_keyword,
  model_savefname,
  'random_intercept',
  print_lmer_output = FALSE
)
influential <- as.numeric(names(cooksd)[(cooksd > (4 / as.numeric(length(unique(
  data$sub
)))))])
data_screen <- data[-influential,]

data_screen %>%
  group_by

# [ PLOT ] reordering for plots _________________________ # nolint
data_screen$cue_name[data_screen$cuetype == "cuetype-high"] <-
  "high cue"
data_screen$cue_name[data_screen$cuetype == "cuetype-low"] <-
  "low cue"

data_screen$stim_name[data_screen$stim == "high"] <-
  "high"
data_screen$stim_name[data_screen$stim == "med"] <-
  "med"
data_screen$stim_name[data_screen$stim == "low"] <-
  "low"

# DATA$levels_ordered <- factor(DATA$param_stimulus_type, levels=c("low", "med", "high"))

data_screen$stim_ordered <- factor(data_screen$stim_name,
                                   levels = c("low", "med", "high"))
data_screen$cue_ordered <- factor(data_screen$cue_name,
                                  levels = c("low cue", "high cue"))
model_iv1 <- "stim_ordered"
model_iv2 <- "cue_ordered"

#  [ PLOT ] calculate mean and se  _________________________
NPSstimcue_subjectwise <- meanSummary(data_screen,
                                      c(subject, model_iv1, model_iv2), dv)
NPSstimcue_groupwise <- summarySEwithin(
  data = NPSstimcue_subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv1, model_iv2),
  idvar = subject
)
NPSstimcue_groupwise$task <- taskname
# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop/29419402

combined_se_calc_cooksd <-
  rbind(combined_se_calc_cooksd, NPSstimcue_groupwise)
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub"
ggtitle <- paste(taskname, " - NPSpos Cooksd removed")
title <- paste(taskname, " - NPSpos")
xlab <- ""
ylab <- "NPSpos (degree)"
ylim <- c(-10, 60)
dv_keyword <- "NPSpos"
if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4575B4", "#D73027")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_task-", taskname, "_rating-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)
g <- plot_halfrainclouds_twofactor(
  NPSstimcue_subjectwise,
  NPSstimcue_groupwise,
  model_iv1,
  model_iv2,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g
```

```{r echo=FALSE, warning=FALSE}
g <- plot_lineplot_twofactor_subsetthick(NPSstimcue_groupwise, taskname = "pain", 
                        iv1 = "stim_ordered", iv2 = "cue_ordered", 
                        mean = "mean_per_sub_norm_mean", error = "se",
                        color = c("low cue" = "#5D5C5C","high cue" = "#D73027"), ggtitle = "Within pain task: CSF as a function of stimulus intensity level and cue", 
                        xlab = "Stimulus intensity", ylab = "Average activation (A.U.)")
g + theme(aspect.ratio=.8)
```
