# (PART\*) Behavioral {.unnumbered}

# Behavioral Rating analysis {#beh-intro .unnumbered}

The following chapters analyze the behavioral ratings -- expectation and outcome ratings -- as a function of experimental variables. I first build the analyses with each factor: cue and stimulus intensity. Then, I include analysis such as shifting trials and analyzing the impact of previous trial ratings on the current rating

- Chapter \@ref(beh-expect-cue) details the cue effect on expectation ratings.

- Chapter \@ref(beh-outcome-cue) examines the cue effect on outcome ratings

- Chapter \@ref(beh-outcome-cueXstim) examines the interaction of cue and stimulus intensity on outcome ratings.

- Chapter \@ref(upgrade_beh-outcome-cueXstim) examines the interaction of cue and stimulus intensity on outcome ratings.



- Chapter \@ref(demean-per-sub-n1) examines the outcome rating as a function of cue, stimulus intensity, expectation ratings, N-1 outcome rating.

## Check if this one produces a line {#beh-sub .unnumbered}

Let's begin by working on your workflow for developing apps.

> this is a text. Let's see if this wraps around\nwill this lead to a line

:::: {.infobox}
Include the actual content here. here are my thoughts
::::

:::: {.todolist}
- convert ratings
- zscore ratings
- calculate relationship
::::

```{r}
# and let me check my code
```
