# (PART\*) ${SECTION NAME} {.unnumbered}

# ${LONGNAME} {#you-can-name-this-section .unnumbered}

The following chapters give you a grab bag of useful techniques.
I think everyone should start with Chapter , because it gives you important tools for developing and debugging apps, and getting help when you're stuck.

After that, there's no prescribed order and relatively few connections between the chapters: I'd suggest quickly skimming to get the lay of the land (and so you might remember these tools if related problems crop up in the future), and otherwise only deeply reading the bits that you currently need.
Here's a quick run down of the main topics:

-   Chapter \@ref(ch2_expect) details the various ways you can layout input and output components on a page, and how you can customise their appearance with themes.

-   Chapter \@ref(ch03_cue) shows you how to add direct interaction to your plot and how to display images generated in other ways.


Let's begin by working on your workflow for developing apps.