---
title: "cue-expectancy_biomarker-NPSVPS_singletrial"
author: "Heejung Jung"
date: "5/13/2022"
output: html_document
---
```{r}
library(psych)
library(car)
library(lmSupport)
library(lme4)
library(lmerTest)
library(plyr)
#library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggpubr)
library(irr)
library(ICC)
source('http://psych.colorado.edu/~jclab/R/mcSummaryLm.R')
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/R_rainclouds.R")
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/summarySE.R")
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/simulateData.R")
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
file.sources = list.files(c("/Users/h/Dropbox/projects_dropbox/social_influence_analysis/scripts/step02_R/utils"),
                          pattern="*.R", 
                          full.names=TRUE, 
                          ignore.case=TRUE)
sapply(file.sources,source,.GlobalEnv)
```

# Functions _____________________________________________________________________


### FUNCTION: normdatawithin
```{r}
normDataWithin <- function(data=NULL, idvar, measurevar, betweenvars=NULL,
                           na.rm=FALSE, .drop=TRUE) {
  ## Norms the data within specified groups in a data frame; it normalizes each
## subject (identified by idvar) so that they have the same mean, within each group
## specified by betweenvars.
##   data: a data frame.
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   na.rm: a boolean that indicates whether to ignore NA's
    library(plyr)

    # Measure var on left, idvar + between vars on right of formula.
    data.subjMean <- ddply(data, c(idvar, betweenvars), .drop=.drop,
     .fun = function(xx, col, na.rm) {
        c(subjMean = mean(xx[,col], na.rm=na.rm))
      },
      measurevar,
      na.rm
    )

    # Put the subject means with original data
    data <- merge(data, data.subjMean)

    # Get the normalized data in a new column
    measureNormedVar <- paste(measurevar, "_norm", sep="")
    data[,measureNormedVar] <- data[,measurevar] - data[,"subjMean"] +
                               mean(data[,measurevar], na.rm=na.rm)

    # Remove this subject mean column
    data$subjMean <- NULL

    return(data)
}
```

### FUNCTION: summarySEwithin
```{r}
summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  ## Summarizes data, handling within-subjects variables by removing inter-subject variability.
## It will still work if there are no within-S variables.
## Gives count, un-normed mean, normed mean (with same between-group mean),
##   standard deviation, standard error of the mean, and confidence interval.
## If there are within-subject variables, calculate adjusted values using method from Morey (2008).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   withinvars: a vector containing names of columns that are within-subjects variables
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message("Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", "))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, "_norm", sep="")

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  df = merge(datac, ndatac)
  return(df)
  
}
```

### FUNCTION: meanSummary
```{r}
meanSummary <- function(DATA, GROUP, DV){
  z <- ddply(DATA, GROUP, .fun = function(xx){
                         c(mean_per_sub = mean(xx[,DV],na.rm=TRUE),
                         sd = sd(xx[,DV],na.rm=TRUE) ) })
  return(z)
  }
```

### FUNCTION: plot_expect_rainclouds
```{r}
# data within_average
# DV = mean_per_sub
# IV = param_cue_type
plot_expect_rainclouds = function(within_average, group_level_condition_average, 
                                  fill_IV, SUB_MEAN, GROUP_MEAN, SE, SUBJECT,
                                  GGTITLE, TITLE, XLAB, YLAB,task_name, w, h, DV_KEYWORD,COLOR, SAVE_FNAME) {
g <- ggplot(data = within_average, 
            aes(y = .data[[SUB_MEAN]], x = factor(.data[[fill_IV]]), fill =  factor(.data[[fill_IV]]))) +
  geom_flat_violin(aes(fill =  factor(.data[[fill_IV]])), position = position_nudge(x = .1, y = 0), 
                   adjust = 1.5, trim = FALSE, alpha = .3, colour = NA) +
  geom_line(data = within_average,
           aes(group = .data[[SUBJECT]], y = .data[[SUB_MEAN]], x = as.numeric( .data[[fill_IV]] )-.15, 
               fill =  factor(.data[[fill_IV]])), linetype = "solid", color = "grey", alpha = .3) +
  geom_point(aes(x = as.numeric( .data[[fill_IV]])-.15, y = .data[[SUB_MEAN]], color = factor(.data[[fill_IV]])),
             position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_boxplot(aes(x =  .data[[fill_IV]], y = .data[[SUB_MEAN]], fill =  .data[[fill_IV]]), width = .1,
               outlier.shape = NA, alpha = 0.8, width = .1, colour = "black") +
  geom_errorbar(data = group_level_condition_average, 
                aes(x = as.numeric( .data[[fill_IV]])+.1, y = as.numeric(.data[[GROUP_MEAN]]), 
                   colour =  factor(.data[[fill_IV]]), 
                   ymin =  .data[[GROUP_MEAN]] - .data[[SE]], 
                   ymax =  .data[[GROUP_MEAN]] + .data[[SE]]), width = .05) +

  # legend stuff __________________________________________________________________________________
  expand_limits(x = 2.8) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  guides(fill=guide_legend(title=TITLE))+
  scale_fill_manual(values = COLOR)+
  scale_color_manual(values = COLOR)+

  ggtitle(GGTITLE) +
  # coord_flip() + #vertical vs horizontal
  xlab(XLAB) +
  ylab(YLAB) +
  theme_bw() 
ggsave(SAVE_FNAME, width = w, height = h)
return(g)

}
```
### FUNCTION: plot_actual_rainclouds
```{r}
plot_actual_rainclouds = function(subjectwise, groupwise, 
                                  IV1, IV2, SUB_MEAN, GROUP_MEAN, SE, SUBJECT, GGTITLE, TITLE, XLAB,YLAB,task_name, w, h, DV_KEYWORD,COLOR,SAVE_FNAME) {

g <- ggplot(data = subjectwise, aes(y = .data[[SUB_MEAN]], x = .data[[IV1]], fill = .data[[IV2]])) +
  geom_flat_violin(aes(fill = .data[[IV2]]), position = position_nudge(x = .1, y = 0), adjust = 1.5,
                   trim = FALSE, alpha = .3, colour = NA) +
  geom_line(data = subjectwise, aes(group = .data[[SUBJECT]], y = .data[[SUB_MEAN]], x = as.numeric(.data[[IV1]])-.15, fill = .data[[IV2]]), linetype = 3, color = "grey") +
  #geom_point(aes(group = subject, x = as.numeric(IV1)-.15, y = mean_per_sub, color = IV2),
 #            position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_point(data = subjectwise, aes(x = as.numeric(.data[[IV1]])-.15, 
                                     y = .data[[SUB_MEAN]], color =.data[[IV2]]),
             position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_boxplot(data = subjectwise, aes(x = .data[[IV1]], y = .data[[SUB_MEAN]], fill = .data[[IV2]]),width = .1,
               outlier.shape = NA, alpha = 0.8, width = .1, colour = "black") +

  # use summary stats __________________________________________________________________________________

  geom_errorbar(data = groupwise, aes(x = as.numeric(.data[[IV1]])+.1, y = .data[[GROUP_MEAN]],
                              group = .data[[IV2]], colour = .data[[IV2]], 
                              ymin = .data[[GROUP_MEAN]] - .data[[SE]], 
                              ymax = .data[[GROUP_MEAN]] + .data[[SE]]), width = .05) +

  # legend stuff __________________________________________________________________________________
  expand_limits(x = 3.25) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  guides(fill=guide_legend(title="social cues"))+
  #scale_color_brewer(palette = "Dark2") +
  #scale_fill_brewer(palette = "Dark2") +
  scale_fill_manual(values = COLOR)+
  scale_color_manual(values = COLOR)+
  ggtitle(GGTITLE) +
  # coord_flip() + #vertical vs horizontal
  xlab("Stimulus intensity levels") +
  ylab("Degrees of actual ratings") +
  theme_bw() 

g
#w = 5
#h = 3

ggsave(SAVE_FNAME, width = w, height = h)

}
```


```{r}
run_cue_lmer = function(DATA,TASKNAME, IV, DV, SUBJECT, DV_KEYWORD, MODEL_SAVE){
  model.cue = lmer( DATA[,DV] ~ DATA[,IV] + (DATA[,IV] | DATA[,SUBJECT]) )
  print(paste("model: ", str_to_title(DV_KEYWORD), " ratings - ", TASKNAME))
  print(summary(model.cue))
  sink(MODEL_SAVE)
  print(summary(model.cue))
  sink()
  cooksd <- cooks.distance(model.cue)
  return(cooksd)
  }
```



# I. STIM l2norm NPS  ______________________________________
## l2norm for stimulus single trials
```{r}

main_dir = '/Volumes/spacetop_projects_social'

# Stim P > VC
p.fname = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-NPS_pain_ev-stim_l2norm.csv'
c.fname = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-NPS_cognitive_ev-stim_l2norm.csv'
v.fname = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-NPS_vicarious_ev-stim_l2norm.csv'
p.df = read.csv(p.fname)
v.df = read.csv(v.fname)
c.df = read.csv(c.fname)
p.df$con = 'pain'
v.df$con = 'vicarious'
c.df$con = 'cognitive'
```

```{r}
pvc <- rbind(p.df, v.df, c.df)
```

```{r}
# parameters for lmer function
pvc$subject = factor(pvc$subject)
pvc$fname_noext = factor(pvc$fname_noext)
data = pvc; iv = 'fname_noext'; dv = 'nps'; subject = 'subject'; dv_keyword = 'nps'
taskname = 'nps'

#directories
local_dir = '/Users/h/Dropbox/projects_dropbox/social_influence_analysis'
analysis_dir <- file.path(local_dir, "analysis", "mixedeffect", "extract_biomarker", "glm_singletrial", as.character(Sys.Date()))
dir.create(analysis_dir, showWarnings = FALSE, recursive = TRUE)
model_savefname <- file.path(
        analysis_dir,
        paste("extract-", taskname, "_glmresults", as.character(Sys.Date()), ".txt",
            sep = ""
        ))

# linear model + cooks d outlier removal
cooksd <- lmer_onefactor_cooksd(
        pvc, taskname, iv, dv, subject, dv_keyword, model_savefname
    )
influential <- as.numeric(names(cooksd)[
(cooksd > (4 / as.numeric(length(unique(data$subject)))))])
data_screen <- data[-influential, ]
```
```{r}
# combhine cell with previous IF IT WORKS

    # summary statistics
    subjectwise <- meanSummary(data_screen, c(subject, iv), dv)
    groupwise <- summarySEwithin(
        data = subjectwise,
        measurevar = "mean_per_sub", # variable created from above
        withinvars = c(iv), # iv
        idvar = "subject"
    )

    subjectwise_mean <- "mean_per_sub";    group_mean <- "mean_per_sub_norm_mean"
    se <- "se";    subject <- "subject"
    ggtitle <- paste(taskname, " - stimulus event, l2normed");    title <- paste(taskname, " - stimulus, l2norm")
    xlab <- "";    ylab <- "nps (dot product)";    
    w = 5; h = 3; dv_keyword <- "expect"
    

    ylim <- c(-30, 30)

    if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
        color <- c('#941100', '#019052','#171893')
    } else {
        color <- c('#941100', '#019052','#171893')
    }
    plot_savefname <- file.path(
        analysis_dir,
        paste("raincloud_task-", taskname,
            "_rating-", dv_keyword,
            "_", as.character(Sys.Date()), ".png",
            sep = ""
        )
    )
    
   g <- plot_rainclouds_onefactor(
        subjectwise, groupwise,
        iv, subjectwise_mean, group_mean, se, subject,
        ggtitle, title, xlab, ylab, task_name,ylim,
        w, h, dv_keyword, color, plot_savefname
    )
   
g +
  scale_x_discrete(labels=c("pain_ev-stim_l2norm" = "Pain", 
                              "vicarious_ev-stim_l2norm" = "Vicarious", 
                              "cognitive_ev-stim_l2norm" = "Cognitive")) +
  theme_classic() 

g
```



# II. STIM l2norm VPS  ______________________________________
## l2norm for stimulus single trials
```{r}

main_dir = '/Volumes/spacetop_projects_social'

# Stim P > VC
p.vps = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-VPS_pain_ev-stim_l2norm.csv'
c.vps = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-VPS_cognitive_ev-stim_l2norm.csv'
v.vps = '/Volumes/spacetop_projects_social/analysis/fmri/spm/multivariate/s04_extract_biomarker/extract-VPS_vicarious_ev-stim_l2norm.csv'
p.vpsdf = read.csv(p.vps)
v.vpsdf = read.csv(v.vps)
c.vpsdf = read.csv(c.vps)
p.vpsdf$con = 'pain'
v.vpsdf$con = 'vicarious'
c.vpsdf$con = 'cognitive'
```

```{r}
pvcvps <- rbind(p.vpsdf, v.vpsdf, c.vpsdf)
```

```{r}
# parameters for lmer function
pvcvps$subject = factor(pvcvps$subject)
pvcvps$fname_noext = factor(pvcvps$fname_noext)
data = pvcvps; iv = 'fname_noext'; dv = 'vps'; subject = 'subject'; dv_keyword = 'vps'
taskname = 'vps'

#directories
local_dir = '/Users/h/Dropbox/projects_dropbox/social_influence_analysis'
analysis_dir <- file.path(local_dir, "analysis", "mixedeffect", "extract_biomarker", "glm_singletrial", as.character(Sys.Date()))
dir.create(analysis_dir, showWarnings = FALSE, recursive = TRUE)
model_savefname <- file.path(
        analysis_dir,
        paste("extract-", taskname, "_glmresults", as.character(Sys.Date()), ".txt",
            sep = ""
        ))

# linear model + cooks d outlier removal
cooksd <- lmer_onefactor_cooksd(
        data, taskname, iv, dv, subject, dv_keyword, model_savefname
    )
influential <- as.numeric(names(cooksd)[
(cooksd > (4 / as.numeric(length(unique(data$subject)))))])
data_screen <- data[-influential, ]
```
```{r}
# combhine cell with previous IF IT WORKS

    # summary statistics
    subjectwise <- meanSummary(data_screen, c(subject, iv), dv)
    groupwise <- summarySEwithin(
        data = subjectwise,
        measurevar = "mean_per_sub", # variable created from above
        withinvars = c(iv), # iv
        idvar = "subject"
    )

    subjectwise_mean <- "mean_per_sub";    group_mean <- "mean_per_sub_norm_mean"
    se <- "se";    subject <- "subject"
    ggtitle <- paste(taskname, " - stimulus event, l2normed");    title <- paste(taskname, " - stimulus, l2norm")
    xlab <- "";    ylab <- "ratings (degree)";    
    w = 5; h = 3; dv_keyword <- "vps"
    

    ylim <- c(-30, 30)

    if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
        color <- c('#171893','#941100', '#019052')
    } else {
        color <- c('#171893','#941100', '#019052')
    }
    plot_savefname <- file.path(
        analysis_dir,
        paste("raincloud_task-", taskname,
            "_rating-", dv_keyword,
            "_", as.character(Sys.Date()), ".png",
            sep = ""
        )
    )
    
    g <- plot_rainclouds_onefactor(
        subjectwise, groupwise,
        iv, subjectwise_mean, group_mean, se, subject,
        ggtitle, title, xlab, ylab, task_name,ylim,
        w, h, dv_keyword, color, plot_savefname
    )
    
    g +
  scale_x_discrete(labels=c("pain_ev-stim_l2norm" = "Pain", 
                              "vicarious_ev-stim_l2norm" = "Vicarious", 
                              "cognitive_ev-stim_l2norm" = "Cognitive")) +
  theme_classic() 
```

















## 1) COPIED FROM OTHER SOURCElmer
```{r}
# parameters _____________________________________ # nolint
subject_varkey <- "src_subject_id"
iv <- "param_cue_type"
dv <- "event02_expect_angle"
dv_keyword <- "expect"
xlab <- ""

ylab <- "ratings (degree)"
subject <- "subject"
exclude <- "sub-0001|sub-0003|sub-0004|sub-0005|sub-0025|sub-0999"

analysis_dir <- file.path(main_dir, "analysis", "mixedeffect", "model01_iv-cue_dv-expect", as.character(Sys.Date()))
dir.create(analysis_dir, showWarnings = FALSE, recursive = TRUE)

for (taskname in c("pain", "vicarious", "cognitive")) {
    model_savefname <- file.path(
        analysis_dir,
        paste("lmer_task-", taskname,
            "_rating-", dv_keyword,
            "_", as.character(Sys.Date()), ".txt",
            sep = ""
        )
    )
    # load data, run model, and exclude outliers
    data <- load_task_social_df(taskname, subject_varkey, iv, dv, exclude)
    data$subject = factor(data$src_subject_id)
    cooksd <- lmer_onefactor_cooksd(
        data, taskname, iv, dv, subject, dv_keyword, model_savefname
    )
    influential <- as.numeric(names(cooksd)[
    (cooksd > (4 / as.numeric(length(unique(data$subject)))))])
    data_screen <- data[-influential, ]
    # summary statistics
    subjectwise <- meanSummary(data_screen, c(subject, iv), dv)
    groupwise <- summarySEwithin(
        data = subjectwise,
        measurevar = "mean_per_sub", # variable created from above
        withinvars = c(iv), # iv
        idvar = "subject"
    )

    subjectwise_mean <- "mean_per_sub";    group_mean <- "mean_per_sub_norm_mean"
    se <- "se";    subject <- "subject"
    ggtitle <- paste(taskname, " - Expectation Rating (degree)");    title <- paste(taskname, " - Expect")
    xlab <- "";    ylab <- "ratings (degree)";    
    w = 5; h = 3; dv_keyword <- "expect"
    if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
        color <- c("#1B9E77", "#D95F02")
    } else {
        color <- c("#4575B4", "#D73027")
    }
    plot_savefname <- file.path(
        analysis_dir,
        paste("raincloud_task-", taskname,
            "_rating-", dv_keyword,
            "_", as.character(Sys.Date()), ".png",
            sep = ""
        )
    )
    plot_rainclouds_onefactor(
        subjectwise, groupwise,
        iv, subjectwise_mean, group_mean, se, subject,
        ggtitle, title, xlab, ylab, task_name,
        w, h, dv_keyword, color, plot_savefname
    )
randEffect$newcoef <- mapvalues(randEffect$term,
    from = c("(Intercept)", 
             "data[, iv]low_cue"
             ),
    to = c("rand_intercept", "rand_cue")
)

rand_subset <- subset(randEffect, select = -c(grpvar, term, condsd))
wide_rand <- spread(rand_subset, key = newcoef, value = condval)

wide_fix <- do.call(
    "rbind",
    replicate(nrow(wide_rand),
        as.data.frame(t(as.matrix(fixEffect))),
        simplify = FALSE
    )
)
rownames(wide_fix) <- NULL
new_wide_fix <- dplyr::rename(wide_fix,
    fix_intercept = `(Intercept)`,
    fix_cue = `data[, iv]low_cue`,
)

total <- cbind(wide_rand, new_wide_fix)
total$task <- taskname
new_total <- total %>% dplyr::select(task, everything())
new_total <- dplyr::rename(total, subj = grp)

rand_savefname <- file.path(
    analysis_dir,
    paste("randeffect_task-", taskname, "_",
        as.character(Sys.Date()), "_outlier-cooksd.csv",
        sep = ""
    )
)
write.csv(new_total, rand_savefname, row.names = FALSE)
}
```