name: Build and Deploy Bookdown

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '16.x'
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.2.2'

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('bookdown')"
      
    - name: Build bookdown
      run: |
        Rscript -e "setwd('scripts/step02_R_bookdown'); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION }}
        publish_dir: scripts/step02_R_bookdown/_book
