on:
  push:
    branches:
      - main

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "devtools", "rmarkdown", "DT", "DescTools", "EMAtools", "GGally", "ICC", "MBESS", "PupillometryR", "RCurl", "TMB", "afex", "bayestestR", "bbmle", "bitops", "boot", "brms", "broom", "caTools", "car", "correlation", "cowplot", "dplyr", "effectsize", "emmeans", "equatiomatic", "extrafont", "gghalves", "ggplot2", "ggpubr", "ggrepel", "ggtext", "glmmTMB", "gridExtra", "htmltools", "knitr", "lavaan", "lme4", "lmerTest", "magrittr", "mediation", "merTools", "patchwork", "plotly", "plyr", "png", "psych", "purrr", "r2mlm", "readr", "reshape", "rstanarm", "scico", "sjPlot", "sjlabelled", "sjmisc", "sjstats", "stats", "stringr", "tidyr", "tidyselect", "tidyverse", "visibly", "yaml"))'
      - name: Render Book
        run: Rscript -e "setwd('scripts/step02_R_bookdown'); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: scripts/step02_R_bookdown/_book/

  # Need to first create an empty gh-pages branch
  # see https://pkgdown.r-lib.org/reference/deploy_site_github.html
  # and also add a secrets for an EMAIL to the repository
  # gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: _book #scripts/step02_R_bookdown/_book  # optional
          # Destination path
          path: _book #scripts/step02_R_bookdown/_book  # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION }}
        with:
          email: ${{ secrets.EMAIL }} # must be a verified email
          build_dir: _book #scripts/step02_R_bookdown/_book             # "_site/" by default

