name: Build and Deploy Bookdown

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '16.x'
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.2'

    - name: Check R package dependencies
      run: |
        Rscript -e "install.packages(c('bookdown', 'devtools', 'rmarkdown', 'DT', 'DescTools', 'EMAtools',
            'GGally', 'ICC', 'MBESS', 'PupillometryR', 'RCurl', 'TMB', 'afex', 'bayestestR', 'bbmle', 
            'bitops', 'boot', 'brms', 'broom', 'caTools', 'car', 'correlation', 'cowplot', 'dplyr', 'effectsize',
            'emmeans', 'equatiomatic', 'extrafont', 'gghalves', 'ggplot2', 'ggpubr', 'ggrepel', 'ggtext', 'glmmTMB',
            'gridExtra', 'htmltools', 'knitr', 'lavaan', 'lme4', 'lmerTest', 'magrittr', 'mediation', 'merTools', 
            'patchwork', 'plotly', 'plyr', 'png', 'psych', 'purrr', 'r2mlm', 'readr', 'reshape', 'rstanarm', 'scico',
            'sjPlot', 'sjlabelled', 'sjmisc', 'sjstats', 'stats', 'stringr', 'tidyr', 'tidyselect', 'tidyverse', 
            'visibly', 'yaml'))"

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/R-packages
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-

    # - name: Install pandoc
    #   uses: r-lib/actions/setup-pandoc@v1
    #   with:
    #     pandoc-version: '2.14'
    - name: Install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14.0.3/pandoc-2.14.0.3-linux-amd64.tar.gz
        tar xvzf pandoc-2.14.0.3-linux-amd64.tar.gz
        sudo mv pandoc-2.14.0.3/bin/* /usr/local/bin/
        rm -rf pandoc-2.14.0.3 pandoc-2.14.0.3-linux-amd64.tar.gz

    - name: Build Bookdown Project
      run: |
        Rscript -e "setwd('scripts/step02_R_bookdown'); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION }}
        publish_dir: scripts/step02_R_bookdown/_book
