on:
  push:
    paths:
      - "scripts/step02_R_bookdown/**"
    branches:
      - main

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install System Dependencies
        run: |
          brew update
          brew install pkg-config || echo "pkg-config already installed"
          brew install qpdf pkgconf checkbashisms ghostscript || echo "Dependencies already installed"
          echo "Checking installed dependencies:"
          brew list
      - name: Check R Package Dependencies
        run: |
          Rscript -e 'install.packages("pkgbuild"); pkgbuild::check_build_tools()'

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages(c("remotes", "devtools"))' 
          Rscript -e 'install.packages(c("afex", "bayestestR", "bookdown", "bbmle", "bitops", "boot", "brms", "broom", "broom.mixed", "car", "caTools", "correlation", "cowplot", "DescTools", "devtools","downlit", "dplyr", "DT", "effectsize", "EMAtools", "emmeans", "extrafont", "FactoMineR", "GGally", "gghalves", "ggplot2", "ggpubr", "ggrepel", "ggtext", "glmmTMB","grid", "gridExtra", "htmltools", "ICC", "jsonlite", "knitr", "kableExtra", "lavaan", "lme4", "lmerTest", "magrittr", "Matrix", "MBESS", "mediation", "merTools", "optimx", "patchwork", "plotly", "plyr", "png", "psych", "PupillometryR", "purrr", "r2mlm", "RColorBrewer", "RCurl", "readr", "reghelper", "reshape", "rmarkdown", "Rmisc", "rstan", "rstanarm", "scico", "semPlot", "sjlabelled", "sjmisc", "sjPlot", "sjstats", "stats", "stringr", "tidyr", "tidyselect", "tidyverse", "TMB","webshot", "yaml"))'
          Rscript -e 'remotes::install_git("https://github.com/jorvlan/raincloudplots.git")'
          Rscript -e 'remotes::install_git("https://github.com/datalorax/equatiomatic.git")'
          Rscript -e 'devtools::install_github("m-clark/visibly")'
          Rscript -e 'devtools::install_github("jungheejung/cueR")'


      - name: Render Book
        #run: Rscript -e "setwd('scripts/step02_R_bookdown'); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
        run: Rscript -e "setwd('scripts/step02_R_bookdown'); bookdown::render_book('index.Rmd', 'bookdown::bs4_book')"
      - uses: actions/upload-artifact@v3
        with:
          name: _book
          path: scripts/step02_R_bookdown/_book/

  # Need to first create an empty gh-pages branch
  # see https://pkgdown.r-lib.org/reference/deploy_site_github.html
  # and also add a secrets for an EMAIL to the repository
  # gh-action from Cecilapp/GitHub-Pages-deploy

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: _book #scripts/step02_R_bookdown/_book  # optional
          # Destination path
          path: _book #scripts/step02_R_bookdown/_book  # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION }}
        with:
          email: ${{ secrets.EMAIL }} # must be a verified email
          build_dir: _book #scripts/step02_R_bookdown/_book             # "_site/" by default

