name: Sync to R Package Repo

on:
  push:
    paths:
      - "scripts/step02_R/utils/**/*.R"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION }}
          repository: jungheejung/cueR # Replace with your R package repo
          event-type: update-r-scripts
