---
title: "behavioral_ICC"
author: "Heejung Jung"
date: "2/22/2022"
output: html_document
---

```{r}
library(psych)
library(car)
library(lmSupport)
library(lme4)
library(lmerTest)
library(plyr)
#library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
#library(Hmisc)
#library(Rmisc)
library(png)
library(knitr)
library(TMB)
library(sjPlot)
library(ggpubr)
library(gridExtra)
library(merTools)
library(sjstats) #to get ICC
library(broom)
library(tidyverse)
library(GGally)
library(RCurl)
library(rstanarm)
library(reshape)
library(boot)
library(afex)
library(cowplot)
library(readr)
library(lavaan)
library(rmarkdown)
library(readr)
library(caTools)
library(bitops)
library(stringr)
## library(extraoperators)
##library(JWileymisc)
##library(multilevelTools)
library(ggpubr)
library(ggrepel)
# library(PupillometryR)
source('http://psych.colorado.edu/~jclab/R/mcSummaryLm.R')
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/R_rainclouds.R")
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/summarySE.R")
source("/Users/h/Documents/projects_local/RainCloudPlots/tutorial_R/simulateData.R")
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
library(r2mlm)
```

# Functions

## a) summary table
http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/#Helper%20functions

```{r FUNCTION - normDataWithin}
normDataWithin <- function(data=NULL, idvar, measurevar, betweenvars=NULL,
                           na.rm=FALSE, .drop=TRUE) {
  ## Norms the data within specified groups in a data frame; it normalizes each
## subject (identified by idvar) so that they have the same mean, within each group
## specified by betweenvars.
##   data: a data frame.
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   na.rm: a boolean that indicates whether to ignore NA's
    library(plyr)

    # Measure var on left, idvar + between vars on right of formula.
    data.subjMean <- ddply(data, c(idvar, betweenvars), .drop=.drop,
     .fun = function(xx, col, na.rm) {
        c(subjMean = mean(xx[,col], na.rm=na.rm))
      },
      measurevar,
      na.rm
    )

    # Put the subject means with original data
    data <- merge(data, data.subjMean)

    # Get the normalized data in a new column
    measureNormedVar <- paste(measurevar, "_norm", sep="")
    data[,measureNormedVar] <- data[,measurevar] - data[,"subjMean"] +
                               mean(data[,measurevar], na.rm=na.rm)

    # Remove this subject mean column
    data$subjMean <- NULL

    return(data)
}
```

```{r FUNCTION - summarySEwithin}
summarySEwithin <- function(data=NULL, measurevar, betweenvars=NULL, withinvars=NULL,
                            idvar=NULL, na.rm=FALSE, conf.interval=.95, .drop=TRUE) {

  ## Summarizes data, handling within-subjects variables by removing inter-subject variability.
## It will still work if there are no within-S variables.
## Gives count, un-normed mean, normed mean (with same between-group mean),
##   standard deviation, standard error of the mean, and confidence interval.
## If there are within-subject variables, calculate adjusted values using method from Morey (2008).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   betweenvars: a vector containing names of columns that are between-subjects variables
##   withinvars: a vector containing names of columns that are within-subjects variables
##   idvar: the name of a column that identifies each subject (or matched subjects)
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
  # Ensure that the betweenvars and withinvars are factors
  factorvars <- vapply(data[, c(betweenvars, withinvars), drop=FALSE],
    FUN=is.factor, FUN.VALUE=logical(1))

  if (!all(factorvars)) {
    nonfactorvars <- names(factorvars)[!factorvars]
    message("Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", "))
    data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
  }

  # Get the means from the un-normed data
  datac <- summarySE(data, measurevar, groupvars=c(betweenvars, withinvars),
                     na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Drop all the unused columns (these will be calculated with normed data)
  datac$sd <- NULL
  datac$se <- NULL
  datac$ci <- NULL

  # Norm each subject's data
  ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop=.drop)

  # This is the name of the new column
  measurevar_n <- paste(measurevar, "_norm", sep="")

  # Collapse the normed data - now we can treat between and within vars the same
  ndatac <- summarySE(ndata, measurevar_n, groupvars=c(betweenvars, withinvars),
                      na.rm=na.rm, conf.interval=conf.interval, .drop=.drop)

  # Apply correction from Morey (2008) to the standard error and confidence interval
  #  Get the product of the number of conditions of within-S variables
  nWithinGroups    <- prod(vapply(ndatac[,withinvars, drop=FALSE], FUN=nlevels,
                           FUN.VALUE=numeric(1)))
  correctionFactor <- sqrt( nWithinGroups / (nWithinGroups-1) )

  # Apply the correction factor
  ndatac$sd <- ndatac$sd * correctionFactor
  ndatac$se <- ndatac$se * correctionFactor
  ndatac$ci <- ndatac$ci * correctionFactor

  # Combine the un-normed means with the normed results
  df = merge(datac, ndatac)
  return(df)
  
}
```

```{r FUNCTION: meanSummary}
meanSummary <- function(DATA, GROUP, DV){
  z <- ddply(DATA, GROUP, .fun = function(xx){
                         c(mean_per_sub = mean(xx[,DV],na.rm=TRUE),
                         sd = sd(xx[,DV],na.rm=TRUE) ) })
  return(z)
  }
```

```{r FUNCTION: expect_df load data}
expect_df = function(TASKNAME, SUBJECT_VARKEY, IV, DV, EXCLUDE ) {
  # INPUT:
  # * TASKNAME (e.g. pain, cognitive, vicarious)
  # * SUBJECT_VARKEY (e.g. src_subject_id or subject)
  # A. load data ______________________________________________________________
  FILENAME = paste('*_task-social_*-' ,TASKNAME, '_beh.csv', sep = "")
  common_path = Sys.glob(file.path(main_dir,'data', 'dartmouth', 'd02_preprocessed_N60',
                                   'sub-*','ses-*',FILENAME))
  # filter_path = common_path[!str_detect(common_path,pattern="sub-0001|sub-0025")]
  filter_path = common_path[str_detect(common_path,pattern="sub-0002|sub-0005|sub-0008|sub-0014|sub-0018|sub-0021|sub-0025|sub-0029|sub-0032|sub-0003|sub-0006|sub-0009|sub-0015|sub-0019|sub-0023|sub-0026|sub-0030|sub-0033|sub-0007|sub-0010|sub-0016|sub-0020|sub-0024|sub-0028|sub-0031|sub-0035")]
  DF <- do.call("rbind",lapply(filter_path,FUN=function(files){ read.csv(files)}))
  is.nan.data.frame <- function(x)
    do.call(cbind, lapply(x, is.nan))
  DF[is.nan(DF)] <- NA

  DF[,"subject"] = factor(DF[,SUBJECT_VARKEY])

  # B. plot expect rating NA ___________________________________________________
  DF_expect_NA = aggregate(DF[,DV], list(DF$subject),function(x) sum(is.na(x)))

  # C. run model ___________________________________________________
  
  DF_remove_NA = DF[!is.na(  DF[DV]  ),]

  DATA <<- as.data.frame(DF_remove_NA)
}
```

```{r FUNCTION: run_cue_lmer }
run_cue_lmer = function(DATA,TASKNAME, IV, DV, SUBJECT, DV_KEYWORD, MODEL_SAVE){
  model.cue = lmer( DATA[,DV] ~ DATA[,IV] + (DATA[,IV] | DATA[,SUBJECT]) + (DATA[,IV] | DATA$session_id))
  print(paste("model: ", str_to_title(DV_KEYWORD), " ratings - ", TASKNAME))
  print(summary(model.cue))
  sink(MODEL_SAVE)
  print(summary(model.cue))
  sink()
  }
```

```{r FUNCTION: run_cue_stim_lmer}
run_cue_stim_lmer = function(DATA,TASKNAME, IV, STIMC1,STIMC2, DV, SUBJECT, DV_KEYWORD, SAVE_FNAME){
  model.full = lmer( DATA[,DV] ~ DATA[,IV]*DATA[,STIMC1] + DATA[,IV]*DATA[,STIMC2] + 
                    (DATA[,IV]*DATA[,STIMC1] + DATA[,IV]*DATA[,STIMC2] | DATA[,SUBJECT])) 
                    # + 
                    # (DATA[,IV]*DATA[,STIMC1] + DATA[,IV]*DATA[,STIMC2] | DATA$session_id))
  sink(SAVE_FNAME)
  print(paste("model: ", str_to_title(DV_KEYWORD), " ratings - ", TASKNAME))
  print(summary(model.full))
  sink()
  print(summary(model.full))
  fixEffect <<- as.data.frame(fixef(model.full))
  randEffect <<-as.data.frame(ranef(model.full))
  return(model.full)
  #View(as.data.frame(fixEffect))
  #View(as.data.frame(randEffect$src_subject_id))
  # A <<- coef(model.full)$src_subject_id
  # B <<- coef(summary(model.full))[ , "Estimate"]
  # return(list(A, B))
  # model_filename = file.path(main_dir, 'analysis', 'semicircle_degree', 
  #                            paste('lmer_task-' ,TASKNAME, '_rating-', DV_KEYWORD,'.txt', sep = ""))

  }
```

```{r FUNCTION: run_cue_stim_ses_lmer}
run_cue_stim_ses_lmer = function(DATA,TASKNAME, IV, STIMC1,STIMC2, SES,DV, SUBJECT, DV_KEYWORD, SAVE_FNAME){
  model.full = lmer( DATA[,DV] ~ DATA[,IV]*DATA[,STIMC1]*DATA[,SES] + DATA[,IV]*DATA[,STIMC2]*DATA[,SES] + 
                    (DATA[,IV]*DATA[,SES]  | DATA[,SUBJECT])) 
  sink(SAVE_FNAME)
  print(paste("model: ", str_to_title(DV_KEYWORD), " ratings - ", TASKNAME))
  print(summary(model.full))
  sink()
  print(summary(model.full))
  SESfixEffect <<- as.data.frame(fixef(model.full))
  SESrandEffect <<-as.data.frame(ranef(model.full))
  return(model.full)
}
```

```{r FUNCTION: plot_expect_rainclouds}

# plot_expect_rainclouds(subjectwise, groupwise, 
#                                   IV, SUB_MEAN, GROUP_MEAN, SE, SUBJECT,
#                                   GGTITLE, TITLE, XLAB, YLAB,task_name, w, h, DV_KEYWORD,COLOR, SAVE_FNAME) 
# 
# FIXplot_expect_rainclouds = function(within_average, group_level_condition_average,  
#                                       GGTITLE, TITLE, XLAB, YLAB, IV, task_name, w, h, COLOR) {
# 
# g <- ggplot(data = within_average, aes(y = mean_per_sub, x = within_average[,IV], fill = within_average[,IV])) +
#   geom_flat_violin(aes(fill = IV), position = position_nudge(x = .1, y = 0), adjust = 1.5,
#                    trim = FALSE, alpha = .5, colour = NA) +
#   geom_line(data = within_average, aes(group = subject, y = mean_per_sub, x = as.numeric(within_average[,IV])-.15, fill = within_average[,IV]), linetype = "solid", color = "grey", alpha = .3) +
#   geom_point(aes(x = as.numeric(within_average[,IV])-.15, y = mean_per_sub, color = within_average[,IV]),
#              position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
#   geom_boxplot(aes(x = within_average[,IV], y = mean_per_sub, fill = within_average[,IV]),width = .1,
#                outlier.shape = NA, alpha = 0.8, width = .1, colour = "black") +
#   geom_errorbar(data = group_level_condition_average, aes(x = as.numeric(group_level_condition_average[,IV])+.1, y = mean_per_sub_norm_mean,
#                              colour = group_level_condition_average[,IV], 
#                               ymin = mean_per_sub_norm_mean-se, 
#                               ymax = mean_per_sub_norm_mean+se), width = .05) +
# 
#   # legend stuff __________________________________________________________________________________
#   expand_limits(x = 2.8) +
#   guides(fill = FALSE) +
#   guides(color = FALSE) +
#   guides(fill=guide_legend(title=TITLE))+
#   scale_fill_manual(values = COLOR)+
#   scale_color_manual(values = COLOR)+
# 
#   ggtitle(GGTITLE) +
#   # coord_flip() + #vertical vs horizontal
#   xlab(XLAB) +
#   ylab(YLAB) +
#   theme_bw() +
# theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
# panel.background = element_blank(), axis.line = element_line(colour = "black"))
# # plot_filename = file.path(main_dir, 'analysis', paste('paingenbias_task-' ,task_name, '_onlyresponse.png', sep = ""))
# # ggsave(plot_filename, width = w, height = h)
# g
# 
# }
```


```{r FUNCTION: plot_expect_rainclouds}
# data within_average
# DV = mean_per_sub
# IV = param_cue_type
plot_expect_rainclouds = function(within_average, group_level_condition_average, 
                                  fill_IV, SUB_MEAN, GROUP_MEAN, SE, SUBJECT,
                                  GGTITLE, TITLE, XLAB, YLAB,task_name, w, h, DV_KEYWORD,COLOR, SAVE_FNAME) {
g <- ggplot(data = within_average, 
            aes(y = .data[[SUB_MEAN]], x = factor(.data[[fill_IV]]), fill =  factor(.data[[fill_IV]]))) +
  geom_flat_violin(aes(fill =  factor(.data[[fill_IV]])), position = position_nudge(x = .1, y = 0), 
                   adjust = 1.5, trim = FALSE, alpha = .3, colour = NA) +
  geom_line(data = within_average,
           aes(group = .data[[SUBJECT]], y = .data[[SUB_MEAN]], x = as.numeric( .data[[fill_IV]] )-.15, 
               fill =  factor(.data[[fill_IV]])), linetype = "solid", color = "grey", alpha = .3) +
  geom_point(aes(x = as.numeric( .data[[fill_IV]])-.15, y = .data[[SUB_MEAN]], color = factor(.data[[fill_IV]])),
             position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_boxplot(aes(x =  .data[[fill_IV]], y = .data[[SUB_MEAN]], fill =  .data[[fill_IV]]), width = .1,
               outlier.shape = NA, alpha = 0.8, width = .1, colour = "black") +
  geom_errorbar(data = group_level_condition_average, 
                aes(x = as.numeric( .data[[fill_IV]])+.1, y = as.numeric(.data[[GROUP_MEAN]]), 
                   colour =  factor(.data[[fill_IV]]), 
                   ymin =  .data[[GROUP_MEAN]] - .data[[SE]], 
                   ymax =  .data[[GROUP_MEAN]] + .data[[SE]]), width = .05) +

  # legend stuff __________________________________________________________________________________
  expand_limits(x = 2.8) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  guides(fill=guide_legend(title=TITLE))+
  scale_fill_manual(values = COLOR)+
  scale_color_manual(values = COLOR)+

  ggtitle(GGTITLE) +
  # coord_flip() + #vertical vs horizontal
  xlab(XLAB) +
  ylab(YLAB) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
ggsave(SAVE_FNAME, width = w, height = h)
return(g)

}
```


```{r FUNCTION: plot_actual_rainclouds}
plot_actual_rainclouds = function(subjectwise, groupwise, 
                                  IV1, IV2, SUB_MEAN, GROUP_MEAN, SE, SUBJECT, GGTITLE, TITLE, XLAB,YLAB,task_name, w, h, DV_KEYWORD,COLOR,SAVE_FNAME) {

g <- ggplot(data = subjectwise, aes(y = .data[[SUB_MEAN]], x = .data[[IV1]], fill = .data[[IV2]])) +
  geom_flat_violin(aes(fill = .data[[IV2]]), position = position_nudge(x = .1, y = 0), adjust = 1.5,
                   trim = FALSE, alpha = .3, colour = NA) +
  geom_line(data = subjectwise, aes(group = .data[[SUBJECT]], y = .data[[SUB_MEAN]], x = as.numeric(.data[[IV1]])-.15, fill = .data[[IV2]]), linetype = 3, color = "grey") +
  #geom_point(aes(group = subject, x = as.numeric(IV1)-.15, y = mean_per_sub, color = IV2),
 #            position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_point(data = subjectwise, aes(x = as.numeric(.data[[IV1]])-.15, 
                                     y = .data[[SUB_MEAN]], color =.data[[IV2]]),
             position = position_jitter(width = .05), size = 1, alpha = 0.8, shape = 20) +
  geom_boxplot(data = subjectwise, aes(x = .data[[IV1]], y = .data[[SUB_MEAN]], fill = .data[[IV2]]),width = .1,
               outlier.shape = NA, alpha = 0.8, width = .1, colour = "black") +

  # use summary stats __________________________________________________________________________________

  geom_errorbar(data = groupwise, aes(x = as.numeric(.data[[IV1]])+.1, y = .data[[GROUP_MEAN]],
                              group = .data[[IV2]], colour = .data[[IV2]], 
                              ymin = .data[[GROUP_MEAN]] - .data[[SE]], 
                              ymax = .data[[GROUP_MEAN]] + .data[[SE]]), width = .05) +

  # legend stuff __________________________________________________________________________________
  expand_limits(x = 3.25) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  guides(fill=guide_legend(title="social cues"))+
  #scale_color_brewer(palette = "Dark2") +
  #scale_fill_brewer(palette = "Dark2") +
  scale_fill_manual(values = COLOR)+
  scale_color_manual(values = COLOR)+
  ggtitle(GGTITLE) +
  # coord_flip() + #vertical vs horizontal
  xlab("Stimulus intensity levels") +
  ylab("Degrees of actual ratings") +
  theme_bw() 

g
#w = 5
#h = 3

ggsave(SAVE_FNAME, width = w, height = h)

}
```

combined expect_df / run_cue_lmer / meanSummary / plot_expect_rainclouds
```{r}
load_and_plot = function(TASKNAME, SUBJECT_VARKEY, IV, DV,DV_KEYWORD, XLAB,YLAB,GGTITLE, TITLE,SUBJECT,EXCLUDE ) {
  # load data
  DATA = expect_df(TASKNAME, SUBJECT_VARKEY, IV, DV, EXCLUDE )
  # run model
  RESULTS = run_cue_lmer(DATA,TASKNAME, IV, DV, SUBJECT, SAVE_FNAME)
  # summarize for plots
  df_d = meanSummary(DATA, c(SUBJECT, IV), DV)
  df_a = summarySEwithin(data=df_d, 
                    measurevar = "mean_per_sub", # variable created from above
                    withinvars = c(IV), # IV
                    idvar = "subject")
  # set color
  if(any(startsWith(DV_KEYWORD, c("expect", "Expect")))){COLOR = c( "#1B9E77", "#D95F02")}else{COLOR=c( "#4575B4", "#D73027")} # if keyword starts with True, color it with orange and green, else, stick with red and blue
  # plot
  GGTITLE = paste(TASKNAME, " - Expectation Rating (degree)")
  TITLE = paste(TASKNAME, " - Expect")
  plot_expect_rainclouds(df_d, df_a, GGTITLE, TITLE, XLAB, YLAB, TASKNAME, 5, 3, DV_KEYWORD,COLOR)
  
  

}
```

```{r rain cloud theme}
raincloud_theme = theme(
text = element_text(size = 10),
axis.title.x = element_text(size = 16),
axis.title.y = element_text(size = 16),
axis.text = element_text(size = 14),
axis.text.x = element_text(angle = 45, vjust = 0.5),
legend.title=element_text(size=16),
legend.text=element_text(size=16),
legend.position = "right",
plot.title = element_text(lineheight=.8, face="bold", size = 16),
panel.border = element_blank(),
panel.grid.minor = element_blank(),
panel.grid.major = element_blank(),
axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))
w = 5
h = 3
```

# load in dataframe

```{r}
# parameters
# TASKNAME = 'cognitive'
SUBJECT_VARKEY = "src_subject_id"
IV = "param_cue_type"
DV = "event02_expect_angle"
DV_KEYWORD = "expect"
XLAB = ""; YLAB = "ratings (degree)"; 

GGTITLE = paste(TASKNAME, " - Expectation Rating (degree)")
TITLE = paste(TASKNAME, " - Expect")
SUBJECT = "subject"
EXCLUDE = ""
analysis_dir =file.path(main_dir,'analysis', 'mixedeffect', 'model04_ICC_actualrating_02-2022')

for (TASKNAME in c("pain", "vicarious", "cognitive")){

SAVE_FNAME = file.path(analysis_dir, paste('lmer_task-', TASKNAME, '_rating-',DV_KEYWORD,'_', as.character(Sys.Date()),'.txt',sep = ''))
DATA = expect_df(TASKNAME, SUBJECT_VARKEY, IV, DV, EXCLUDE )
}
```

```{r}
FILENAME = paste('*_task-social_*-' ,TASKNAME, '_beh.csv', sep = "")
common_path = Sys.glob(file.path(main_dir,'data', 'dartmouth', 'd02_preprocessed', 'sub-*','ses-*',FILENAME))
filter_path = common_path[!str_detect(common_path,pattern="sub-0001|sub-0003|sub-0004|sub-0005|sub-0025")]

DF <- do.call("rbind",lapply(filter_path,FUN=function(files){ read.csv(files)}))
is.nan.data.frame <- function(x)
  do.call(cbind, lapply(x, is.nan))
DF[is.nan(DF)] <- NA
DF = as.data.frame(DF)
# subjects as factor
DF$subject = factor(DF$src_subject_id)
```

```{r}
# subjectwise = meanSummary(DF, c(src_subject_id, session_id), event04_actual_angle)
# groupwise = summarySEwithin(data=subjectwise, 
#                   measurevar = "mean_per_sub", # variable created from above
#                     withinvars = c(IV), # IV
#                     idvar = "subject")
# 
main_dir = '/Users/h/Dropbox/projects_dropbox/social_influence_analysis'
for (TASKNAME in c("pain","vicarious","cognitive")){
  print(TASKNAME)
  DV_KEYWORD = "actual-rating"
FILENAME = paste('*_task-social_*-' ,TASKNAME, '_beh.csv', sep = "")
common_path = Sys.glob(file.path(main_dir,'data', 'dartmouth', 'd02_preprocessed', 'sub-*','ses-*',FILENAME))
filter_path = common_path[!str_detect(common_path,pattern="sub-0001|sub-0003|sub-0004|sub-0005|sub-0025")]

DF <- do.call("rbind",lapply(filter_path,FUN=function(files){ read.csv(files)}))
is.nan.data.frame <- function(x)
  do.call(cbind, lapply(x, is.nan))
DF[is.nan(DF)] <- NA
DF = as.data.frame(DF)
# subjects as factor
DF$subject = factor(DF$src_subject_id)
SUBJECT = "src_subject_id"
IV = "session_id"
DV = "event04_actual_angle"
# DF$subject = factor(DF$src_subject_id)
# DATA = subset(DF, param_task_name == TASKNAME)
# DATA$task <- factor(DATA$task, levels = c("pain-early", "pain-late", "pain-post", "pain-plateau", "pain"))
DF[is.nan(DF)]<-NA
subjectwise_ses = meanSummary(DF, c("subject", IV), DV)
subjectwise_ses[is.nan(subjectwise_ses)]<-NA
# groupwise_ses = summarySEwithin(data=subjectwise_ses, 
#                   measurevar = "mean_per_sub", # variable created from above
#                     withinvars = c(IV), # IV
#                     idvar = "subject")
# groupwise_drop_ses <- na.omit(groupwise_ses)

# long to wide

ses_beh = subset(subjectwise_ses,select = c("subject", "session_id", "mean_per_sub"))
ses_beh[is.nan(ses_beh)]<-NA
ses_beh_wide = reshape(ses_beh, idvar = "subject", timevar = "session_id", direction = "wide")
sub_ses = ses_beh_wide[rowSums(is.na(ses_beh_wide[,-1])) != ncol(ses_beh_wide[,-1]), ]
sub_13 = sub_ses[,c("mean_per_sub.1", "mean_per_sub.3")]
c13 = psych::ICC(sub_13[complete.cases(sub_13),])
icc13 = irr::icc(
  sub_13[complete.cases(sub_13),], model = "twoway", 
  type = "agreement", unit = "average"
  )
# print(icc13)
icc13_text = c13$results$ICC[5]# icc13_text = c13$results$ICC[5]

c34 = psych::ICC(sub_ses[,c("mean_per_sub.3", "mean_per_sub.4")])
icc34 = irr::icc(
  sub_ses[,c("mean_per_sub.3", "mean_per_sub.4")], model = "twoway", 
  type = "agreement", unit = "average"
  )
# print(icc34)
icc34_text = c34$results$ICC[5]

c41 = psych::ICC(sub_ses[,c("mean_per_sub.4", "mean_per_sub.1")])
ses41 = irr::icc(
  sub_ses[,c("mean_per_sub.4", "mean_per_sub.1")], model = "twoway", 
  type = "agreement", unit = "average"
  )
icc41_text = c41$results$ICC[5]

beh13 = ggplot(data = sub_ses, aes(x = mean_per_sub.1, y = mean_per_sub.3)) +
  stat_smooth(method = 'lm', color = "black") + 
  geom_point(size = 2, alpha = .8) +
  xlab("sesion 1") + ylab("session 3") + xlim(0, 150) + ylim(0, 200) +
  theme_classic() +
  theme(axis.title = element_text(size = 20))  +
    annotate(geom = "text", x = 120, y = 200, 
           label = as.character(paste("ICC = ",format(icc13_text, digits = 2),sep = "")),
           color = "black", size = 5)

beh34 = ggplot(data = sub_ses, aes(x = mean_per_sub.3, y = mean_per_sub.4)) +
  stat_smooth(method = 'lm', color = "black") + 
  geom_point(size = 2, alpha = .8) +
  xlab("session 3") + ylab("session 4") + xlim(0, 150) + ylim(0, 200) +
  theme_classic() +
  theme(axis.title = element_text(size = 20))  +
    annotate(geom = "text", x = 120, y = 200, 
           label = as.character(paste("ICC = ",format(icc34_text, digits = 2),sep = "")),
           color = "black", size = 5)

beh41 = ggplot(data = sub_ses, aes(x = mean_per_sub.4, y = mean_per_sub.1)) +
  stat_smooth(method = 'lm', color = "black") + 
  geom_point(size = 2, alpha = .8) +
  xlab("session 4") + ylab("session 1") + xlim(0, 150) + ylim(0, 200) +
  theme_classic() + 
  theme(axis.title = element_text(size = 20))  +
  annotate(geom = "text", x = 120, y = 200, 
           label = as.character(paste("ICC = ",format(icc41_text, digits = 2),sep = "")),
           color = "black", size = 5)


ggpubr::ggarrange(beh13,beh34,beh41,ncol = 3, nrow = 1, common.legend = FALSE,legend = "bottom")
plot_filename = file.path(main_dir, 'analysis','mixedeffect','model04_behavioral_ICC', paste('socialinfluence_task-',TASKNAME,'_',DV_KEYWORD,'_icc','_', as.character(Sys.Date()),'.png', sep = ""))
ggsave(plot_filename, width = 10, height = 3)
}
```



# calculate average rating per session across participants
# row: sub-num
# columns: ses 1,3,4

# calculate 
